class LocalizationPun {
  static const Map<String, String> translations = {
    'cattle': 'ਪਸ਼ੂ',
    'feed': 'ਫੀਡ',
    'transaction': 'ਲੇਣ-ਦੇਣ',
    'avg_milk': 'ਔਸਤ ਦੁੱਧ',
    'dry_cows': 'ਸੂਕੀ ਗਾ',
    'RF ID': "ਪਸ਼ੂ ਆਈਡੀ",
    'Heifer': 'ਵੇਹੜ੍ਹ ',
    "Total Count": "ਕੁੱਲ ਗਿਣਤੀ",
    "semen sale": "ਵੀਰਜ ਦੀ ਵਿਕਰੀ",
    "Green Fodder": "ਹਰਾ ਚਾਰਾ",
    "Dry Fodder": "ਸੁੱਕਾ ਚਾਰਾ",
    "Concentrate": "ਘਣੀ ਚਾਰਾ",
    'breed': 'ਨਸਲ',
    "sex": "ਲਿੰਗ",
    "new_cattle": "ਨਵੇਂ ਪਸ਼ੂ",
    "gender": "ਲਿੰਗ",
    "enter_the_DOB": "ਜਨਮ ਮਿਤੀ ਦਰਜ ਕਰੋ",
    "enter_the_weight": "ਵਜਨ ਦਰਜ ਕਰੋ",
    "source_of_cattle": "ਪਸ਼ੂਆਂ ਦਾ ਸੋਰਸ",
    "select_the_breed": "ਨਸਲ ਚੁਣੋ",
    "status": "ਹਾਲਤ",
    'isPregnant': 'ਗਰਭਵਤੀ ਹੈ',
    "Animals": "ਜਾਨਵਰ",
    'no': 'ਨਹੀਂ',
    'yes': 'ਹਾਂ',
    "male": "ਨਰ",
    "female": "ਮਾਦਾ",
    "born on farm": "ਫਾਰਮ 'ਚ ਪੈਦਾ ਹੋਇਆ",
    "purchased": "ਖਰੀਦਿਆ ਗਿਆ",
    "Milked": "ਦੁੱਧ ਦਿੰਦੇ",
    "Milk Details": "ਦੁੱਧ ਦੇ ਵੇਰਵੇ",
    "insemination": "ਗਰਭਾਧਾਨ",
    "abortion": "ਗਰਭਪਾਤ",
    "Dry": "ਸੂਖਾ",
    "dry": "ਸੂਖਾ",
    "Calf": "ਵੱਛਾ",
    "calved": "ਵਾਛ ਬਈ ਗਾਈ",
    "pregnant": "ਗਰਭਵਤੀ",
    "submit": "ਪ੍ਰਸਤੁਤ",
    "search_cattle": "ਪਸ਼ੂ ਖੋਜੋ",
    "state": "ਹਾਲਤ",
    'all': 'ਸਭ',
    'sahiwal': 'ਸਾਹਿਵਾਲ',
    'gir': 'ਗਿਰ',
    'jersey': 'ਜਰਸੀ',
    'holstein': 'ਹੋਲਸਟਿਨ',
    "filter_options": "ਫਿਲਟਰ ਚੋਣਾਂ",
    "confirm_filters": "ਫਿਲਟਰ ਪੁਸ਼ਟੀ ਕਰੋ",
    "clear_filters": "ਫਿਲਟਰ ਮਿਟਾਓ",
    'vaccination': 'ਟੀਕਾ ਲਗਾਉਣਾ',
    'please_wait': 'ਕਿਰਪਾ ਕਰਕੇ ਰੁਕੋ ...',
    'events': 'ਘਟਨਾਵਾਂ',
    'add_event': "ਘਟਨਾਵਾਂ ਸ਼ਾਮਲ ਕਰੋ",
    'details': "ਵੇਰਵਾ",
    'age': "ਉਮਰ",
    "dob": "ਜਨਮ ਤਾਰੀਖ",
    "weight": "ਭਾਰ",
    "milk_records": "ਦੁੱਧ ਦਾ ਰਿਕਾਰਡ",
    "date": "ਤਾਰੀਖ਼",
    "total_milk": "ਕੁੱਲ ਦੁੱਧ:",
    "litre": "ਲੀ.",
    "add_milk_data": "ਦੁੱਧ ਦਾ ਡਾਟਾ ਸ਼ਾਮਲ ਕਰੋ",
    "select_rfid": " ਪਸ਼ੂ ਆਈਡੀ ਚੁਣੋ",
    "morning_milk": "ਸਵੇਰ ਦਾ ਦੁੱਧ (ਲਿਟਰ)",
    "evening_milk": "ਸ਼ਾਮ ਦਾ ਦੁੱਧ (ਲਿਟਰ)",
    "milking_date": "ਦੁੱਧ ਨਿਕਾਲਣ ਦੀ ਮਿਤੀ",
    "add": " ਸ਼ਾਮਲ ਕਰੋ",
    "please_select_rfid": " ਕਿਰਪਾ ਕਰਕੇ ਪਸ਼ੂ ਆਈਡੀ ਚੁਣੋ",
    "please_enter_value": "ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਮੁੱਲ ਦਾਖਲ ਕਰੋ",
    "please_choose_date": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਮਿਤੀ ਚੁਣੋ",
    "morning": "ਸਵੇਰ",
    "evening": "ਸ਼ਾਮ",
    "total": "ਕੁੱਲ",
    "milk_sale": "ਦੁੱਧ ਵੇਚਣ",
    "cattle_sale": "ਪਸੂ ਵੇਚਣ",
    "other": "ਹੋਰ",
    "income": "ਆਮਦਨ",
    "expenses": "ਖਰਚ",
    'transactions': "ਲੇਨ-ਦੇਨ",
    "amount": "ਰਕਮ",
    "on_date": " ਤਾਰੀਖ ਤੇ",
    "Feed": "ਚਾਰਾ",
    "Inventory": "ਵਸਤੂ ਸੂਚੀ",
    "Maize": "ਮਕਕਾ",
    "Barley": "ਜੌ",
    "Mustard": "ਸਰੋਂ",
    "Rye Grass": "ਰਾਈ ਘਾਹ",
    "Bajra": "ਬਾਜਰਾ",
    "Sorghum": "ਜੁਆਰ",
    "Berseem": "ਬਰਸੀਮ",
    "Oats": "ਜਈ",
    "Others": "ਹੋਰ",
    "Veterinary": "ਪਸ਼ੂ ਚਿਕਿੱਤਸਾ",
    "Labor Costs": "ਮਜ਼ਦੂਰੀ ਖਰਚ",
    "Equipment and Machinery": "ਉਪਕਰਣ ਅਤੇ ਮਸ਼ੀਨਰੀ",
    "total_transactions": "ਕੁੱਲ ਲੇਨ-ਦੇਨ",
    "date_range": "ਮਿਤੀ ਦੀ ਸੀਮਾ:",
    "total_income": "ਕੁੱਲ ਆਮਦਨ",
    "income_per_category": "ਆਮਦਨ ਦਾ ਵਰਗ",
    "total_expense": "ਕੁੱਲ ਖਰਚ",
    "expense_per_category": "ਖਰਚ ਦਾ ਵਰਗ",
    "net_profit": "ਨੇਟ ਲਾਭ",
    "net_loss": "ਨੇਟ ਨੁਕਸਾਨ",
    "Milk Sale": "ਦੁੱਧ  ਵੇਚਣ",
    "Cattle Sale": "ਪਸੂ ਵੇਚਣ",
    "date_of_income": "ਆਮਦਨ ਦੀ ਮਿਤੀ",
    "how_much_did_you_earn": "ਤੁਸੀਂ ਕਿੰਨਾ ਕਮਾਇਆ (₹ ਵਿੱਚ)",
    "select_income_type": "ਆਮਦਨ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    "enter_category": "ਵਰਗ ਦਾਖਲ ਕਰੋ",
    "new_income": "ਨਵੀਂ ਆਮਦਨ",
    "Other": "ਹੋਰ",
    "new_expense": "ਨਵਾਂ ਖਰਚ",
    "date_of_expense": "ਖਰਚ ਦੀ ਮਿਤੀ",
    "how_much_did_you_spend": "ਤੁਸੀਂ ਕਿੰਨਾ ਖਰਚ ਕੀਤਾ (₹ ਵਿੱਚ)",
    "select_expense_type": "ਖਰਚ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    "edit_income": "ਆਮਦਨ ਸੰਪਾਦਿਤ ਕਰੋ",
    "edit_expense": "ਖਰਚ ਸੰਪਾਦਿਤ ਕਰੋ",
    "income_category": "ਆਮਦਨ ਕੈਟੇਗਰੀ",
    "expense_category": "ਖਰਚ ਕੈਟੇਗਰੀ",
    "transaction_date": "ਲੇਨ-ਦੇਨ ਦੀ ਮਿਤੀ",
    "enter_transaction_amount": "ਲੇਨ-ਦੇਨ ਰਕਮ ਦਾਖਲ ਕਰੋ",
    "delete": "ਹਟਾਓ",
    "save": "ਸੰਭਾਲੋ",
    "expiry_date": "ਮਿਆਦ ਦੀ ਮਿਤੀ",
    "current_stock": "ਮੌਜੂਦਾ ਭੰਡਾਰ",
    "current_need": "ਮੌਜੂਦਾ ਜ਼ਰੂਰਤ",
    "add_feed_item": "ਚਾਰਾ ਆਈਟਮ ਸ਼ਾਮਲ ਕਰੋ",
    "item_name": "ਆਈਟਮ ਦਾ ਨਾਮ",
    "quantity": "ਮਾਤਰਾ",
    "required_quantity": "ਲੋੜੀਦਾ ਮਾਤਰਾ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "edit_feed_item": "ਚਾਰਾ ਆਈਟਮ ਸੋਧੋ",
    "need": "ਲੋੜ",
    "stock": "ਸਟਾਕ",
    "new_cattle_added_successfully": "ਨਵੀਂ ਪਸ਼ੂ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ ਹੈ",
    'notifications': "ਸੂਚਨਾਵਾਂ",
    "provide nutritional feed with high protein and fibre content":
        "ਉੱਚ ਪ੍ਰੋਟੀਨ ਅਤੇ ਫਾਈਬਰ ਸਮੱਗਰੀ ਵਾਲਾ ਪੋਸ਼ਣ ਚਾਰਾ ਪ੍ਰਦਾਨ ਕਰੋ",
    "is expected to go dry": "ਸੂਕਾ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ ਹੈ",
    "Heat alert": "ਗਰਮੀ ਦੀ ਚੇਤਾਵਨੀ",
    "is due for pregnancy test": "ਗਰਭਧਾਰਣ ਟੈਸਟ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",
    "is due for calving": "ਬੱਛੇ ਦੇ ਜਨਮ ਦਾ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",
    "is ready for milking": "ਦੁੱਧ ਦੁਹਾਈ ਲਈ ਤਿਆਰ ਹੈ",
    "is due for Insemination": "ਕ੍ਰਿਤਰਿਮ ਗਰਭਧਾਰਣ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",
    "is due for deworming vaccination": "ਕੀੜੇ ਮਾਰ ਟੀਕੇ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",
    "is due for brucellosis vaccination": "ਬਰੂਸੈਲੋਸਿਸ ਟੀਕੇ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",
    "is due for modified theileriosis vaccination":
        "ਸੋਧਿਤ ਥਾਈਲਰੀਓਸਿਸ ਟੀਕੇ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",
    "Dry Alert": "ਸੂਖਾ ਚੱਕਰ ਚੇਤਾਵਨੀ",
    "Heat Alert": "ਗਰਮੀ ਦੀ ਚੇਤਾਵਨੀ",
    "Pregnancy Test Alert": "ਗਰਭਧਾਰਣ ਟੈਸਟ ਚੇਤਾਵਨੀ",
    "Calving Alert": "ਬੱਛੇ ਦੇ ਜਨਮ ਦੀ ਚੇਤਾਵਨੀ",
    "Milking Alert": "ਦੁੱਧ ਦੁਹਾਈ ਚੇਤਾਵਨੀ",
    "AI Alert": "ਕ੍ਰਿਤਰਿਮ ਗਰਭਧਾਰਣ ਚੇਤਾਵਨੀ",
    "Deworming Vax Alert": "ਕੀੜੇ ਮਾਰ ਟੀਕੇ ਦੀ ਚੇਤਾਵਨੀ",
    "Brucellosis Vax Alert": "ਬਰੂਸੈਲੋਸਿਸ ਟੀਕੇ ਦੀ ਚੇਤਾਵਨੀ",
    "Modified Theileriosis Vax Alert": "ਸੋਧਿਤ ਥਾਈਲਰੀਓਸਿਸ ਟੀਕੇ ਦੀ ਚੇਤਾਵਨੀ",
    "Nutritional Feed Alert": "ਪੋਸ਼ਣ ਚਾਰਾ ਚੇਤਾਵਨੀ",
    "Cow": "ਗਾਂ",
    "Buffalo": "ਮੱਝ",
    "Total Milk": "ਕੁੱਲ ਦੁੱਧ",
    "Litres": "ਲਿਟਰ",
    "unknown_item": "ਅਣਜਾਣ ਆਈਟਮ",
    "Rate": "ਦਰ",
    "Source": "ਸਰੋਤ",
    "own farm": "ਖੁਦ ਦਾ ਫਾਰਮ",
    'Enter custom type': 'ਕਸਟਮ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    'Quantity': 'ਮਾਤਰਾ',
    'Wheat Straw': 'ਕਣਕ ਦਾ ਭੂਸਾ',
    'Paddy Straw': 'ਧਾਨ ਦਾ ਭੂਸਾ',
    'Unit': 'ਇਕਾਈ',
    'Kg': 'ਕਿਲੋ',
    'Quintal': 'ਕੁਇੰਟਲ',
    'Rate per Unit': 'ਇਕਾਈ ਪ੍ਰਤੀ ਦਰ',
    'Total Price': 'ਕੁੱਲ ਕੀਮਤ',
    'Calculate': 'ਗਣਨਾ ਕਰੋ',
    'Save': 'ਸੇਵ ਕਰੋ',
    'Type': 'ਕਿਸਮ',
    'Quantity/Yield': 'ਮਾਤਰਾ / ਪੈਦਾਵਾਰ',
    'Land Area(in acres)': 'ਜਮੀਨ ਦਾ ਖੇਤਰਫਲ (ਏਕੜਾਂ ਵਿੱਚ)',
    'Seed Cost': 'ਬੀਜ ਦੀ ਲਾਗਤ',
    'Fertilizers Cost': 'ਖਾਦ ਦੀ ਲਾਗਤ',
    'Inoculants Cost': 'ਇਨੋਕੁਲੈਂਟਸ ਦੀ ਲਾਗਤ',
    'Labor Cost': 'ਮਜਦੂਰੀ ਦੀ ਲਾਗਤ',
    'Diesel Cost': 'ਡੀਜ਼ਲ ਦੀ ਲਾਗਤ',
    'Total Production Cost': 'ਕੁੱਲ ਉਤਪਾਦਨ ਦੀ ਲਾਗਤ',
    "De-Oiled Rice Bran": "ਡੀ-ਆਇਲਡ ਚੌਲ ਦੀ ਭੂਸੀ",
    "Soyabean": "ਸੋਆਬੀਨ",
    "Wheat Bran": "ਗੰਢੀ ਦੀ ਭੂਸੀ",
    "DCP": "ਡੀਸੀਪੀ",
    "LSP": "ਐਲਐਸਪੀ",
    "Salt": "ਨਮਕ",
    "Sodium Bicarbonate": "ਸੋਡੀਅਮ ਬਾਈਕਾਰਬੋਨੇਟ",
    "Nicen": "ਨਾਈਸਿਨ",
    "Urea": "ਯੂਰੀਆ",
    "Mineral Mixture": "ਖਣਿਜ ਮਿਸ਼ਰਣ",
    'homemade': 'ਘਰੇਲੂ',
    'Enter Custom Homemade Type': 'ਕਸਟਮ ਘਰੇਲੂ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    'Select Ingredients:': 'ਸਮਗਰੀ ਚੁਣੋ:',
    'Enter its cost': 'ਇਸ ਦੀ ਕੀਮਤ ਦਰਜ ਕਰੋ',
    'Custom Type cannot be empty!': 'ਕਸਟਮ ਕਿਸਮ ਖਾਲੀ ਨਹੀਂ ਹੋ ਸਕਦੀ!',
    'Enter Custom Purchased Type': 'ਕਸਟਮ ਖਰੀਦਿਆ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    'Purchased Ingredients': 'ਖਰੀਦੀਆਂ ਸਮਗਰੀਆਂ',
    'Homemade Ingredients': 'ਘਰੇਲੂ ਸਮਗਰੀਆਂ',
    'Total Income': 'ਕੁੱਲ ਆਮਦਨ',
    "Search Cattle": "ਪਸ਼ੂ ਖੋਜੋ",
    "Dairy Sangrah Registration": "ਡੇਅਰੀ ਸੰਗ੍ਰਹਿ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    "Get into Existing Farm": "ਮੌਜੂਦਾ ਫਾਰਮ ਵਿੱਚ ਪ੍ਰਵੇਸ਼ ਕਰੋ",
    "Get started with your farm management journey":
        "ਆਪਣੀ ਫਾਰਮ ਪ੍ਰਬੰਧਨ ਯਾਤਰਾ ਦੀ ਸ਼ੁਰੂਆਤ ਕਰੋ",
    "Confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
    "Sign Up": "ਰਜਿਸਟਰ ਕਰੋ",
    "Enter Your Phone Number": "ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    "Phone Number": "ਫ਼ੋਨ ਨੰਬਰ",
    "Login To Dairy Sangrah": "ਡੇਅਰੀ ਸੰਗ੍ਰਹਿ ਵਿੱਚ ਲੌਗਿਨ ਕਰੋ",
    "Didn't receive code?": "ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ?",
    "Resend OTP": "ਓਟੀਪੀ ਮੁੜ ਭੇਜੋ",
    "Continue": "ਜਾਰੀ ਰੱਖੋ",
    "Enter OTP": "ਓਟੀਪੀ ਦਰਜ ਕਰੋ",
    "Register a New Farm": "ਨਵਾਂ ਫਾਰਮ ਰਜਿਸਟਰ ਕਰੋ",
    'No existing Farm!': 'ਕੋਈ ਮੌਜੂਦਾ ਫਾਰਮ ਨਹੀਂ ਹੈ!',
    'Not Registered Content':
        "ਇਸ ਨੰਬਰ ਨਾਲ ਕੋਈ ਫਾਰਮ ਰਜਿਸਟਰ ਨਹੀਂ ਹੈ। ਨਵਾਂ ਫਾਰਮ ਰਜਿਸਟਰ ਕਰਨ ਲਈ ਕਿਰਪਾ ਕਰਕੇ 'ਰਜਿਸਟਰ' ਚੁਣੋ ਜਾਂ ਵਾਪਸ ਜਾਣ ਲਈ 'ਰੱਦ ਕਰੋ' ਚੁਣੋ!",
    'register': 'ਰਜਿਸਟਰ',
    'cancel': 'ਰੱਦ ਕਰੋ',
    'Owner Name': 'ਮਾਲਕ ਦਾ ਨਾਮ',
    'Phone No.': 'ਫੋਨ ਨੰਬਰ',
    'Farm Name': 'ਫਾਰਮ ਦਾ ਨਾਮ',
    'Farm Address': 'ਫਾਰਮ ਦਾ ਪਤਾ',
    'Profile': 'ਪ੍ਰੋਫਾਈਲ - ਵੈਯਕਤਿਕ ਜਾਣਕਾਰੀ',
    'Log out': 'ਲਾਗ ਆਉਟ ਕਰੋ',
    'Delete Data': 'ਡਾਟਾ ਹਟਾਓ',
    "Are you Sure?": 'ਕੀ ਤੁਸੀਂ ਨਿਸ਼ਚਿਤ ਹੋ?',
    'Delete Data Content':
        "ਇਹ ਕਾਰਵਾਈ ਸਾਰੇ ਫਾਰਮ ਡਾਟੇ ਨੂੰ ਹਮੇਸ਼ਾਂ ਲਈ ਹਟਾ ਦੇਵੇਗੀ, ਪਰ ਫਾਰਮ ਫਿਰ ਵੀ ਰਜਿਸਟਰ ਰਹੇਗਾ। ਅੱਗੇ ਵੱਧਣ ਲਈ 'ਹਾਂ' ਚੁਣੋ ਜਾਂ ਵਾਪਸ ਜਾਣ ਲਈ 'ਰੱਦ ਕਰੋ' ਚੁਣੋ!",
    'Delete Account': 'ਖਾਤਾ ਹਟਾਓ',
    'Delete Account Content':
        "ਇਹ ਕਾਰਵਾਈ ਸਾਰੇ ਯੂਜ਼ਰ ਅਤੇ ਫਾਰਮ ਡਾਟੇ ਨੂੰ ਹਮੇਸ਼ਾਂ ਲਈ ਹਟਾ ਦੇਵੇਗੀ। ਕਿਰਪਾ ਕਰਕੇ ਅੱਗੇ ਵੱਧਣ ਲਈ 'ਹਟਾਓ' ਚੁਣੋ ਜਾਂ ਵਾਪਸ ਜਾਣ ਲਈ 'ਰੱਦ ਕਰੋ' ਚੁਣੋ!",
    're-login': 'ਦੁਬਾਰਾ ਲਾਗਇਨ ਕਰੋ',
    'requires recent login': 'ਹਾਲ ਹੀ ਵਿੱਚ ਲਾਗਇਨ ਕਰਨਾ ਜ਼ਰੂਰੀ ਹੈ!',
    're_login content':
        "ਕਿਰਪਾ ਕਰਕੇ 'ਦੁਬਾਰਾ ਲਾਗਇਨ ਕਰੋ' ਚੁਣੋ ਅਤੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ, ਜਾਂ 'ਰੱਦ ਕਰੋ' ਚੁਣੋ ਵਾਪਸ ਜਾਣ ਲਈ!",
    'More Options': 'ਹੋਰ ਵਿਕਲਪ',
    'Edit Profile': 'ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ',
    'Error in Fetch': 'ਡਾਟਾ ਪ੍ਰਾਪਤੀ ਵਿੱਚ ਗਲਤੀ',
    'Save Changes': 'ਬਦਲਾਵ ਸੇਵ ਕਰੋ',
    'Deleted': 'ਹਟਾ ਦਿੱਤਾ ਗਿਆ',
    'edit_details': 'ਵੇਰਵੇ ਸੋਧੋੋ',
    'please_select_gender': 'ਕਿਰਪਾ ਕਰਕੇ ਲਿੰਗ ਚੁਣੋ',
    'please_select_source': 'ਕਿਰਪਾ ਕਰਕੇ ਸਰੋਤ ਚੁਣੋ',
    'please_select_breed': 'ਕਿਰਪਾ ਕਰਕੇ ਨਸਲ ਚੁਣੋ',
    'cattle_details_updated_successfully': 'ਵੇਰਵਾ ਸਫਲਤਾਪੂਰਕ ਅੱਪਡੇਟ ਹੋਇਆ!!',
    'event_name': 'ਘਟਨਾ ਦਾ ਨਾਮ',
    'event_date': 'ਘਟਨਾ ਦਾ ਤਾਰੀਖ਼',
    'please_select_event_and_date': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਘਟਨਾ ਅਤੇ ਤਾਰੀਖ ਚੁਣੋ',
    'please_enter_tag_num': 'ਕਿਰਪਾ ਕਰਕੇ ਟੈਗ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    'please_select_cattle_type': 'ਕਿਰਪਾ ਕਰਕੇ ਪਸ਼ੂ ਦਾ ਕਿਸਮ ਚੁਣੋ',
    'list_is_empty': 'ਸੂਚੀ ਖਾਲੀ ਹੈ',
    'no_entries_for_sel_date': 'ਚੁਣੀ ਗਈ ਤਾਰੀਖ ਲਈ ਕੋਈ ਐਂਟਰੀ ਨਹੀਂ ਹੈ',
    'edit_milk_data': 'ਦੂਧ ਦਾ ਡਾਟਾ ਸੰਪਾਦਿਤ ਕਰੋ',
    'enter_valid_num': 'ਠੀਕ ਸੰਖਿਆ ਦਾਖਲ ਕਰੋ',
    'add_transaction': 'ਲੈਣ-ਦੇਣ ਸ਼ਾਮਲ ਕਰੋ',
    'no_matching_price': 'ਮਿਲਦੀ ਜੁਲਦੀ ਕੀਮਤ ਨਹੀਂ ਮਿਲੀ -',
    'fat': 'ਫੈਟ',
    'snf': 'ਐਸਐਨਐਫ',
    'err_msg': 'ਗਲਤੀ ਸੰਦੇਸ਼',
    'OK': 'ਠੀਕ ਹੈ',
    'please_sel_income_type': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਆਯ ਕੌਣ ਚੁਣੋ',
    'please_enter_category_other':
        "ਕਿਰਪਾ ਕਰਕੇ 'ਹੋਰ' ਆਯ ਕੌਣ ਲਈ ਇੱਕ ਸ਼੍ਰੇਣੀ ਦਰਜ ਕਰੋ",
    'please_sel_milk_buyer': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਦੁਧ ਖਰੀਦਦਾਰ ਚੁਣੋ',
    'please_sel_fat_snf_qty':
        'ਕਿਰਪਾ ਕਰਕੇ ਫੈਟ, ਐਸਐਨਐਫ ਅਤੇ ਮਾਤਰਾ ਦੇ ਮੁੱਲ ਦਰਜ ਕਰੋ',
    'fat_snf_qty_val_chk':
        'ਫੈਟ, ਐਸਐਨਐਫ ਅਤੇ ਮਾਤਰਾ ਵੈਧ ਸੰਖਿਆਵਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ ਜੋ ਜ਼ੀਰੋ ਤੋਂ ਵੱਡੀਆਂ ਹੋਣ',
    'no_price_fat_snf':
        'ਦਿੱਤੇ ਗਏ ਫੈਟ ਅਤੇ ਐਸਐਨਐਫ ਲਈ ਦੁਧ ਦੀ ਕੀਮਤ ਦਾ ਡਾਟਾ ਨਹੀਂ ਮਿਲਿਆ',
    'please_enter_tot_income': 'ਕਿਰਪਾ ਕਰਕੇ ਕੁੱਲ ਆਯ ਦਰਜ ਕਰੋ',
    'sel_feed_consumption': 'ਚਾਰੇ ਦੀ ਖਪਤ ਚੁਣੋ :',
    'out_of_stock': 'ਸਟਾਕ ਖਤਮ ਹੋ ਗਿਆ ਹੈ, ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਭਰੋ!',
    'enter_qty_consumed_kg': 'ਵਰਤੀ ਗਈ ਮਾਤਰਾ (ਕਿਲੋ ਵਿੱਚ) ਦਰਜ ਕਰੋ',
    'cannot_be_more_than_existing': 'ਮੌਜੂਦਾ ਮਾਤਰਾ ਨਾਲੋਂ ਵੱਧ ਨਹੀਂ ਹੋ ਸਕਦੀ!',
    "amul": "ਅਮੂਲ",
    "verka": "ਵੈਰਕਾ",
    "nestle": "ਨੇਸਲੇ",
    "d to c": "ਸਿੱਧਾ ਗਾਹਕ ਤੱਕ",
    'start': 'ਆਰੰਭ',
    'end': 'ਅੰਤ',
    'data_del_msg': 'ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ, ਡਾਟਾ ਮਿਟਾਇਆ ਜਾ ਰਿਹਾ ਹੈ!',
    "Land Area (in acres)": "ਜ਼ਮੀਨ ਦਾ ਖੇਤਰਫਲ (ਏਕੜ ਵਿੱਚ)",
    "app_version": "ਐਪ ਸੰસ્કਰਨ",
    "Select Language": "ਭਾਸ਼ਾ ਚੁਣੋ",
    "English": "ਅੰਗਰੇਜ਼ੀ",
    "Hindi": "ਹਿੰਦੀ",
    "Punjabi": "ਪੰਜਾਬੀ",
    "Telugu": "ਤੈਲੁਗੂ",
    "Preferred Language": "ਪਸੰਦ ਦੀ ਭਾਸ਼ਾ",
    "Cattle Groups": "ਪਸ਼ੂ ਸਮੂਹ",
    "new_cattle_group": "ਨਵਾਂ ਪਸ਼ੂ ਸਮੂਹ",
    'crossbred jersey': 'ਕ੍ਰਾਸਬ੍ਰੀਡ ਜਰਸੀ',
    'crossbred HF': 'ਕ੍ਰਾਸਬ੍ਰੀਡ ਏਚਐਫ',
    'amritmahal': 'ਅੰਮ੍ਰਿਤਮਹਿਲ',
    'hariana': 'ਹਰਿਆਣਾ',
    'ongole': 'ਓੰਗੋਲ',
    'tharparkar': 'ਥਾਰਪਾਰਕਰ',
    'red sindhi': 'ਲਾਲ ਸਿੰਧੀ',
    'red kandhari': 'ਲਾਲ ਕੰਧਾਰੀ',
    'rathi': 'ਰਾਠੀ',
    'kankrej': 'ਕੰਕਰੇਜ',
    'krishna valley': 'ਕ੍ਰਿਸ਼ਨਾ ਵੈਲੀ',
    'nagori': 'ਨਾਗੋਰੀ',
    'murrah': 'ਮੁਰਾਹ',
    'nili ravi': 'ਨੀਲੀ ਰਾਵੀ',
    'bhadawari': 'ਭਦਾਵਰੀ',
    'surti': 'ਸੁਰਤੀ',
    'jaffarabadi': 'ਜਫਰਾਬਾਦੀ',
    'mehsana': 'ਮਹਿਸਾਣਾ',
    'pandharpuri': 'ਪੰਢਰਪੁਰੀ',
    'banni': 'ਬੰਨੀ',
    "enter_cattle_count_to_add": "ਜੋੜਨ ਲਈ ਪਸ਼ੂਆਂ ਦੀ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "grpid": "ਸਮੂਹ ਆਈਡੀ",
    "cattle_count": "ਪਸ਼ੂ ਗਿਣਤੀ",
    "new_cattle_grp_added_successfully":
        "ਨਵਾਂ ਪਸ਼ੂ ਸਮੂਹ ਸਫਲਤਾ ਨਾਲ ਜੋੜਿਆ ਗਿਆ!!",
    "App Mode": "ਐਪ ਮੋਡ",
    "whole farm": "ਪੂਰਾ ਫਾਰਮ",
    "group wise": "ਸਮੂਹ ਅਨੁਸਾਰ",
    "cattle wise": "ਪਸ਼ੂ ਅਨੁਸਾਰ",
    "milk_entry_type": "ਦੁੱਧ ਦਰਜ ਕਰੋ ਕਿਸਮ",
    "select_grpid": "ਸਮੂਹ ਆਈਡੀ ਚੁਣੋ",
    "ID": "ਆਈਡੀ",
    "enter_breed_count": "ਨਸਲਾਂ ਦੀ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "welcome_msg_onboard":
        "ਬਸ ਥੋੜ੍ਹੇ ਹੋਰ ਕਦਮ !!!\n\nਕੀ ਤੁਸੀਂ ਪਸ਼ੂਆਂ ਨੂੰ ਨਸਲ ਵਾਂਗ ਸਮੂਹ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋਂ?",
    "cow_breed_msg_onboard":
        "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ ਤੁਹਾਡੇ ਫਾਰਮ ਵਿੱਚ ਗਾਂ ਦੀਆਂ ਕਿਨ੍ਹਾਂ ਨਸਲਾਂ ਹਨ?",
    "cow_count_msg_onboard":
        "ਕਿਰਪਾ ਕਰਕੇ ਹਰ ਗਾਂ ਕੈਟੇਗਰੀ ਲਈ ਪਸ਼ੂਆਂ ਦੀ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "buffalo_breed_msg_onboard":
        "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ ਤੁਹਾਡੇ ਫਾਰਮ ਵਿੱਚ ਮੱਝ ਦੀਆਂ ਕਿਨ੍ਹਾਂ ਨਸਲਾਂ ਹਨ?",
    "buffalo_count_msg_onboard":
        "ਕਿਰਪਾ ਕਰਕੇ ਹਰ ਮੱਝ ਕੈਟੇਗਰੀ ਲਈ ਪਸ਼ੂਆਂ ਦੀ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "breed_wise_title": "ਨਸਲ ਅਨੁਸਾਰ ਅੱਗੇ ਵਧੋ?",
    "cow_count_title": "ਗਾਂ ਦੀ ਗਿਣਤੀ",
    "cow_breeds_title": "ਗਾਂ ਦੀਆਂ ਨਸਲਾਂ",
    "buffalo_breeds_title": "ਮੱਝ ਦੀਆਂ ਨਸਲਾਂ",
    "buffalo_count_title": "ਮੱਝ ਦੀ ਗਿਣਤੀ",
    "enter_for_breed": "ਵੇਰਵਾ ਦਾਖਲ ਕਰੋ - ਨਸਲ",
    "enter_the_details": "ਵੇਰਵਾ ਦਾਖਲ ਕਰੋ",
    "enter_calf_count": "ਵੱਛਾ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "enter_heifer_count": "ਵੇਹੜ੍ਹ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "enter_milked_count": "ਦੁੱਧ ਦਿੰਦੇ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "enter_dry_count": "ਸੂਖਾ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    "enter_male_count": "ਨਰ ਪਸ਼ੂਆਂ ਦੀ ਗਿਣਤੀ ਦਾਖਲ ਕਰੋ",
    'Adult Male': 'ਬਾਲਗ ਨਰ',
    'select': 'ਚੁਣੋ',
    'Existing Cattle Count': 'ਉਪਰੋਕਤ ਚੋਣ ਲਈ ਮੌਜੂਦਾ ਗਿਣਤੀ',
    'cattle_grp_exists': "ਇਹ ਸਮੂਹ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ!",
    'want_to_add_more_cattle': "ਇਸ ਸਮੂਹ ਵਿੱਚ ਹੋਰ ਪਸ਼ੂ ਸ਼ਾਮਲ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    'total_groups': 'ਕੁੱਲ ਸਮੂਹ',
    'total_cattle': 'ਕੁੱਲ ਪਸ਼ੂ',
    'Update_gender_dob':
        'ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਪਸ਼ੂ ਲਈ ਲਿੰਗ ਅਤੇ ਜਨਮ ਤਾਰੀਖ ਅਪਡੇਟ ਕਰੋ ਤਾਂ ਜੋ ਇਵੈਂਟ ਮਹਲ ਹੋ ਸਕਣ ਅਤੇ ਉਚਿਤ ਸੂਚਨਾਵਾਂ ਮਿਲ ਸਕਣ!',
    'enter_the_cattle_name': 'ਪਸ਼ੂ ਦਾ ਨਾਮ / ਟੈਗ ਨੰਬਰ ਦਾਖਲ ਕਰੋ',
    'please_select_status': 'ਕਿਰਪਾ ਕਰਕੇ ਸਥਿਤੀ ਚੁਣੋ',
    'cattle_name': 'ਨਾਮ / ਟੈਗ ਨੰਬਰ',
    'add_new_cattle': 'ਨਵਾਂ ਪਸ਼ੂ ਜੋੜੋ',
    "enter_sire_info": "ਨਰ ਪਸ਼ੂ ਦੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰੋ",
    "enter_notes": "ਜੇ ਕੋਈ ਤੁਰੰਤ ਨੋਟ ਹਨ ਤਾਂ ਦਰਜ ਕਰੋ",
    "enter_mother_info": "ਮਾਤਾ ਦੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰੋ",
    "enter_father_info": "ਪਿਤਾ ਦੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰੋ",
    "mother_info": "ਮਾਤਾ ਦੀ ਜਾਣਕਾਰੀ",
    "father_info": "ਪਿਤਾ ਦੀ ਜਾਣਕਾਰੀ",
    "calf_entry": "ਨਵੇਂ ਜੰਮੇ ਬੱਛੇ ਦੀ ਐਂਟਰੀ",
    "would_enter_calf_details": "ਹੁਣ ਨਵੇਂ ਜੰਮੇ ਬੱਛੇ ਦੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰਨ ਦਾ ਸਮਾਂ ਹੈ!",
    "now": "ਹੁਣੇ ਕਰੋ",
    "later": "ਬਾਅਦ ਵਿੱਚ",
    "notes": "ਨੋਟਸ",
    "sire_info": "ਨਰ ਪਸ਼ੂ :"
  };
}
