class LocalizationEn {
  static const Map<String, String> translations = {
    'Cow': 'Cow',
    'Buffalo': 'Buffalo',
    'calve': 'Calve',
    'Type': 'Type',
    'Register a New Farm': 'Register a New Farm',
    'Phone Number': 'Phone Number',
    'Sign Up': 'Sign Up',
    'Enter Your Phone Number': 'Enter Your Phone Number',
    'Login To Dairy Sangrah': 'Login To Dairy Sangrah',
    "Didn't receive code": "Didn't receive code",
    'Resend OTP': 'Resend OTP',
    'Continue': 'Continue',
    'Enter OTP': 'Enter OTP',
    'cattle': 'Cattle',
    'feed': 'Feed',
    'Calf': 'Calf',
    'ai': 'Ai',
    'transaction': 'Transaction',
    'avg_milk': 'Avg Milk',
    'dry_cows': 'Dry Cows',
    'RF ID': "Cattle Id",
    "breed": 'Breed',
    "sex": "Sex",
    'new_cattle': 'New Cattle',
    'gender': 'Gender',
    'enter_the_DOB': 'Enter the Date of Birth',
    'enter_the_weight': 'Enter the Weight',
    'source_of_cattle': 'Source of Cattle',
    'select_the_breed': 'Select the Breed',
    'status': 'Status',
    'isPregnant': 'Is Pregnant',
    'no': 'No',
    'yes': 'Yes',
    'male': 'Male',
    'female': 'Female',
    'born on farm': 'Born on Farm',
    'purchased': 'Purchased',
    'Milked': 'Milked',
    'Heifer': 'Heifer',
    'insemination': 'Insemination',
    "semen sale": "semen sale",
    'abortion': 'Abortion',
    'Dry': 'Dry',
    'dry': 'Dry',
    'calved': 'Calved',
    'pregnant': 'Pregnant',
    'submit': 'Submit',
    'search_cattle': 'Search Cattle',
    'state': 'State',
    'all': 'All',
    'sahiwal': 'Sahiwal',
    'gir': 'Gir',
    'jersey': 'Jersey',
    'holstein': 'Holstein (HF)',
    'filter_options': 'Filter Options',
    'confirm_filters': 'Confirm Filters',
    'clear_filters': 'Clear Filters',
    'vaccination': 'Vaccination',
    'please_wait': 'Please wait ...',
    'events': "Events",
    'add_event': "Add Event",
    'details': "Details",
    "age": "Age",
    "dob": "DOB",
    "weight": "Weight",
    "milk_records": "Milk Records",
    "date": "Date",
    "total_milk": "Total Milk:",
    "litre": "L",
    "Litres": "Litres",
    "add_milk_data": "Add Milk Data",
    "select_rfid": "Select Cattle ID",
    "morning_milk": "Morning Milk (Litres)",
    "evening_milk": "Evening Milk (Litres)",
    "milking_date": "Milking Date",
    "Source": "Source",
    "add": "Add",
    "please_select_rfid": "Please select Cattle ID",
    "please_enter_value": "Please enter a value",
    "please_choose_date": "Please choose a date",
    "morning": "Morning",
    "evening": "Evening",
    "total": "Total",
    "transactions": "Transactions",
    "milk_sale": "Milk Sale",
    "cattle_sale": "Cattle Sale",
    "other": "Other",
    "income": "Income",
    "expenses": "Expenses",
    "amount": "Amount",
    "on_date": "On Date",
    "Maize": "Maize",
    "Barley": "Barley",
    "Mustard": "Mustard",
    "Rye Grass": "Rye Grass",
    "Bajra": "Bajra",
    "Sorghum": "Sorghum",
    "Berseem": "Berseem",
    "Oats": "Oats",
    "Others": "Others",
    "Feed": "Feed",
    "Animals": "Animals",
    "Green Fodder": "Green Fodder",
    "Dry Fodder": "Dry Fodder",
    "Concentrate": "Concentrate",
    "Total Count": "Total Count",
    "Inventory": "Inventory",
    "own farm": "Own Farm",
    "Veterinary": "Veterinary",
    "Labor Costs": "Labor Costs",
    "Equipment and Machinery": "Equipment and Machinery",
    "total_transactions": "Total Transactions",
    "date_range": "Date range:",
    "total_income": "Total Income",
    "income_per_category": "Income per Category",
    "total_expense": "Total Expense",
    "expense_per_category": "Expense per Category",
    "net_profit": "Net Profit",
    "net_loss": "Net Loss",
    "Cattle Sale": "Cattle Sale",
    "Milk Sale": "Milk Sale",
    'Calculate': 'Calculate',
    'Save': 'Save',
    "Get started with your farm management journey":
        "Get started with your farm management journey",
    "date_of_income": "Date of Income",
    "Dairy Sangrah Registration": "Dairy Sangrah Registration",
    "Get into Existing Farm": "Get into Existing Farm",
    'Confirm': 'Confirm',
    "how_much_did_you_earn": "How much did you earn (in ₹)",
    "select_income_type": "Select Income type",
    "enter_category": "Enter Category",
    "new_income": "New Income",
    "new_expense": "New Expense",
    'Rate per Unit': 'Rate per Unit',
    'Quantity': 'Quantity',
    'Total Price': 'Total Price',
    'Quantity/Yield': "Quantity/Yield",
    "Other": "Other",
    "date_of_expense": "Date of expense",
    "how_much_did_you_spend": "How much did you spend (in ₹)",
    "select_expense_type": "Select Expense type",
    "edit_income": "Edit Income",
    "edit_expense": "Edit Expense",
    "income_category": "Income Category",
    "expense_category": "Expense Category",
    "transaction_date": "Transaction Date",
    "enter_transaction_amount": "Enter Transaction Amount",
    "delete": "Delete",
    "save": "Save",
    "expiry_date": "Expiry Date",
    "current_stock": "Current Stock",
    "current_need": "Current Need",
    "add_feed_item": "Add Feed Item",
    "item_name": "Item Name",
    "quantity": "Quantity",
    "required_quantity": "Required Quantity",
    "category": "Category",
    "edit_feed_item": "Edit Feed Item",
    'Enter Custom Purchased Type': 'Enter Custom Purchased Type',
    'Enter Custom Homemade Type': 'Enter Custom Homemade Type',
    'Enter its cost': 'Enter its cost',
    'De-Oiled Rice Bran': 'De-Oiled Rice Bran',
    'Soyabean': 'Soyabean',
    'Wheat Bran': 'Wheat Bran',
    'DCP': 'DCP',
    'LSP': 'LSP',
    'Salt': 'Salt',
    'Sodium Bicarbonate': 'Sodium Bicarbonate',
    'Nicen': 'Nicen',
    'Urea': 'Urea',
    'Mineral Mixture': 'Mineral Mixture',
    'Custom Type cannot be empty!': 'Custom Type cannot be empty!',
    'Select Ingredients:': 'Select Ingredients:',
    "need": "Need",
    "stock": "Stock",
    'homemade': 'Homemade',
    'new_cattle_added_successfully': "New Cattle Added Successfully!!",
    'notifications': "Notifications",
    'No existing Farm!': 'No existing Farm!',
    'Not Registered Content':
        'There is no farm registered with this number.Please choose REGISTER to register as a new Farm or choose CANCEL to go back!',
    'register': 'Register',
    'cancel': 'Cancel',
    'Owner Name': 'Owner Name',
    'Phone No.': 'Phone No.',
    'Farm Name': 'Farm Name',
    'Farm Address': 'Farm Address',
    'Profile': 'Profile',
    'Log out': 'Log out',
    'Delete Data': 'Delete Data',
    "Are you Sure?": "Are you Sure?",
    'Delete Data Content':
        'This will delete all the farm data permanently but the farm still remains registered. Please choose YES to continue and CANCEL to go back!',
    'Delete Account': 'Delete Account',
    'Delete Account Content':
        "This will delete all the user and farm data permanently. Please choose DELETE to continue and CANCEL to go back!",
    're-login': 'Re-Login',
    'requires recent login': 'This action requires recent login!',
    're_login content':
        'Please choose Re-LOGIN and try again or choose CANCEL to go back!',
    'More Options': 'More Options',
    'Edit Profile': 'Edit Profile',
    'Error in Fetch': 'Error in Fetch',
    'Save Changes': 'Save Changes',
    'Deleted': 'Deleted',
    'edit_details': 'Edit Details',
    'please_select_gender': 'Please select gender',
    'please_select_source': 'Please select source',
    'please_select_breed': 'Please select breed',
    'cattle_details_updated_successfully':
        'Cattle details updated Successfully!!',
    'event_name': 'Event Name',
    'event_date': 'Event Date',
    'please_select_event_and_date': 'Please select an event and date',
    'please_enter_tag_num': 'Please enter tag number',
    'please_select_cattle_type': 'Please select type of cattle',
    'list_is_empty': 'The list is empty!',
    'no_entries_for_sel_date': 'No entries found for selected date!',
    'edit_milk_data': 'Edit Milk Data',
    'enter_valid_num': 'Please enter a valid number',
    'add_transaction': 'Add Transaction',
    'no_matching_price': 'No matching price found for',
    'fat': 'Fat',
    'snf': 'SNF',
    'err_msg': 'Error Message',
    'OK': 'OK',
    'please_sel_income_type': 'Please select an income type',
    'please_enter_category_other':
        "Please enter a category for 'Other' income type",
    'please_sel_milk_buyer': 'Please select a milk buyer',
    'please_sel_fat_snf_qty': 'Please enter Fat, SNF, and Quantity values',
    'fat_snf_qty_val_chk':
        'Fat, SNF, and Quantity must be valid numbers greater than zero',
    'no_price_fat_snf': 'Milk price data not found for the given Fat and SNF',
    'please_enter_tot_income': 'Please enter the total income',
    'sel_feed_consumption': 'Select Feed Consumption :',
    'out_of_stock': 'Out of Stock, please refill!',
    'enter_qty_consumed_kg': 'Enter qty consumed in Kg',
    'cannot_be_more_than_existing': 'cannot be more than existing quantity!',
    'Unit': 'Unit',
    'Kg': 'Kg',
    'Quintal': 'Quintal',
    "amul": "Amul",
    "verka": "Verka",
    "nestle": "Nestle",
    "d to c": "D to C",
    'start': 'Start',
    'end': 'End',
    'Rate': 'Rate',
    'data_del_msg': 'Please wait, data deletion in process!',
    "Land Area(in acres)": "Land Area(in acres)",
    "Seed Cost": "Seed Cost",
    "Fertilizers Cost": "Fertilizers Cost",
    "Inoculants Cost": "Inoculants Cost",
    "Labor Cost": "Labor Cost",
    "Diesel Cost": "Diesel Cost",
    "Total Production Cost": "Total Production Cost",
    "app_version": "App Version",
    "Select Language": "Select Language",
    "English": "English",
    "Hindi": "Hindi",
    "Punjabi": "Punjabi",
    "Telugu": "Telugu",
    "Preferred Language": "Preferred Language",
    "Cattle Groups": "Cattle Groups",
    "new_cattle_group": "New Cattle Group",
    'crossbred jersey': 'Crossbred Jersey',
    'crossbred HF': 'Crossbred HF',
    'amritmahal': 'Amritmahal',
    'hariana': 'Hariana',
    'ongole': 'Ongole',
    'tharparkar': 'Tharparkar',
    'red sindhi': 'Red Sindhi',
    'red kandhari': 'Red Kandhari',
    'rathi': 'Rathi',
    'kankrej': 'Kankrej',
    'krishna valley': 'Krishna Valley',
    'nagori': 'Nagori',
    'murrah': 'Murrah',
    'nili ravi': 'Nili Ravi',
    'bhadawari': 'Bhadawari',
    'surti': 'Surti',
    'jaffarabadi': 'Jaffarabadi',
    'mehsana': 'Mehsana',
    'pandharpuri': 'Pandharpuri',
    'banni': 'Banni',
    "enter_cattle_count_to_add": "Enter the number of cattle you wish to add",
    "grpid": "Group Id",
    "cattle_count": "Cattle Count",
    "new_cattle_grp_added_successfully":
        "New Cattle Group Added Successfully!!",
    "App Mode": "App Mode",
    "whole farm": "Whole Farm",
    "group wise": "Group Wise",
    "cattle wise": "Cattle Wise",
    "milk_entry_type": "Milk entry Type",
    "select_grpid": "Select Group Id",
    "ID": "ID",
    "enter_breed_count": "Enter the no. of breeds",
    "welcome_msg_onboard":
        "Just a few more steps !!!\n\nWould you like to group the cattle breed wise?",
    "cow_breed_msg_onboard":
        "Please provide the number of cow breeds you have in your farm?",
    "cow_count_msg_onboard":
        "Please enter the cattle count for each cow categories",
    "buffalo_breed_msg_onboard":
        "Please provide the number of buffalo breeds you have in your farm?",
    "buffalo_count_msg_onboard":
        "Please enter the cattle count for each buffalo categories",
    "breed_wise_title": "Proceed Breed wise?",
    "cow_count_title": "Cows Count",
    "cow_breeds_title": "Cow Breeds",
    "buffalo_breeds_title": "Buffalo Breeds",
    "buffalo_count_title": "Buffaloes Count",
    "enter_for_breed": "Enter details for Breed",
    "enter_the_details": "Enter the details",
    "enter_calf_count": "Enter Calf count",
    "enter_heifer_count": "Enter Heifer count",
    "enter_milked_count": "Enter Milked count",
    "enter_dry_count": "Enter Dry count",
    "enter_male_count": "Enter Male cattle count",
    'Adult Male': 'Adult Male',
    'select': 'Select',
    'Existing Cattle Count': 'Existing count for chosen criteria',
    'cattle_grp_exists': "This group criteria already exists!",
    'want_to_add_more_cattle': "Want to add more cattle to this group?",
    'total_groups': 'Total Groups',
    'total_cattle': 'Total Cattle',
    'Update_gender_dob':
        'Please update Gender and Date of birth for this Cattle to add events and receive appropriate notifications!',
    'enter_the_cattle_name': 'Enter the Cattle Name / Tag No.',
    'please_select_status': 'Please select status',
    'cattle_name': 'Name / Tag No.',
    'add_new_cattle': 'Add New Cattle',
    'enter_sire_info': 'Enter Sire Information',
    'enter_notes': 'Enter quick notes if any',
    'enter_mother_info': 'Enter Mother Information',
    'enter_father_info': 'Enter Father Information',
    'mother_info': 'Mother Info.',
    'father_info': 'Father Info.',
    'calf_entry': 'New Born Calf Entry',
    'would_enter_calf_details': "It's time to make the entry for the new born Calf!",
    'now': 'Proceed Now',
    'later': 'Later',
    'notes': 'Notes',
    'sire_info': 'Sire :',
    'reports': 'Reports',
    'milk production': 'Milk Production',
    'milk sale': 'Milk Sale',
    'report_type': 'Report Type',
    'generate_report': 'Generate Report',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'please_enter_qty': 'Please enter Quantity',
    'select_report_type': 'Please select report type',
    'reports_available': 'Reports Available',
  };
}
