class LocalizationHi {
  static const Map<String, String> translations = {
    'cattles': 'पशु',
    'Register a New Farm':'एक नया फार्म पंजीकृत करें',
    'feed': 'चारा',
    'Cow':'गाय',
    'Buffalo':'भैंस',
    'transaction': 'लेन-देन',
    'avg_milk': 'औसत दूध',
    'dry_cows': 'सूखी गायें',
    'RF ID':"आरएफ आईडी",
    'Search Cattle':'पशु खोजें',
    'Breed':'नस्ल',
    'breed':'नस्ल',
    'Sex':'लिंग',
    'sex':'लिंग',
    'new_cattle':'नये पशु',
    'enter_the_rfid':'आरएफआईडी दर्ज करें ',
    'gender':'लिंग',
    'enter_the_DOB':'जन्मतिथि दर्ज करें',
    'enter_the_weight':'वजन दर्ज करें ',
    'source_of_cattle':'पशुओं का स्रोत',
    'enter_the_breed':'नस्ल दर्ज करें',
    'status':'स्थिति',
    'isPregnant': 'गर्भवती है',
    'no': 'नहीं',
    'yes': 'हाँ',
    'male':'नर',
    'Female':'मादा',
    'female':'मादा',
    'born_on_farm':'खेत में जन्मा',
    'purchased':'खरीदा गया',
    'Milked':'दुही',
    'milked':'दुही',
    'Heifer':'बछिया',
    'heifer':'बछिया',
    'insemination':'गर्भाधान',
    'abortion':'गर्भपात ',
    'Dry':'सूखी',
    'dry':'सूखी',
    'calf':'बछड़ा',
    'Calf':'बछड़ा',
    "Animals":"पशु",
    "Green Fodder":"हरा चारा",
    "Dry Fodder":"सूखा चारा",
    "Concentrate":"सांद्र",
    'calved':'वाछ ब्याई गाय',
    'pregnant':'गर्भवती',
    'submit':'प्रस्तुत',
    'search_cattle':'पशु खोजें',
    'state':'स्थिति',
    'sahiwal':'सहिवाल',
    'Gir':'गिर',
    'Jersey':'जर्सी',
    'Holstein':'होल्स्टीन',
    'All':'सभी',
    'filter_options':'फ़िल्टर विकल्प',
    'confirm_filters':'फ़िल्टर सत्यापित करें',
    'clear_filters':'फ़िल्टर मिटाएं',
    'vaccination':'टीकाकरण',
    'please_wait':'कृपया प्रतीक्षा करें ...',
    'events':'घटनाएं',
    "add_event":"घटनाएँ जोड़ें",
    'details':"विवरण",
    "age":"आयु",
    "dob":"जन्म तिथि",
    "weight":"वज़न",
    "Total Count":"कुल गिनती",
    'Total Income':'कुल आय',
    "semen sale":"वीर्य बिक्री",
    "milk_records":"दूध का रिकॉर्ड",
    "date":"दिनांक",
    "Total Milk":"कुल दूध",
    "litre":"लि.",
    "add_milk_data":"दूध के डेटा जोड़ें",
    "select_rfid":"आरएफआईडी का चयन करें",
    "morning_milk":"सुबह का दूध",
    "evening_milk":"शाम का दूध",
    "milking_date":" दूध निकालने की तारीख",
    "add":"जोड़ें",
    "please_select_rfid":"कृपया आरएफआईडी का चयन करें",
    "please_enter_value": "कृपया मूल्य दर्ज करें",
    "please_choose_date": "कृपया एक तारीख चुनें",
    "morning":"सुबह",
    "evening":"शाम",
    "total":"कुल",
    "milk_sale":"दूध बिक्री",
    "cattle_sale":"पशु बिक्री",
    "other":"अन्य",
    "income":"आय",
    "expenses":"व्यय",
    "transactions":"लेन-देन",
    "amount":"राशि",
    "on_date":"तिथि",
    "Maize":"मक्का",
    "Barley":"जौ",
    "Mustard":"सरसों",
    "Rye Grass":"राई घास",
    "Bajra":"बाजरा",
    "Sorghum":"ज्वार",
    "Barseem":"बरसीम",
    "Oats":"जई",
    "Others":"अन्य",
    "Feed": "चारा",
    "Inventory": "भंडार",
    "Veterinary": "पशुचिकित्सा",
    "Labor Costs": "श्रम लागत",
    "Equipment and Machinery": "उपकरण और मशीनरी",
    "total_transactions": "कुल लेन-देन",
    "date_range": "तिथि सीमा:",
    "total_income": "कुल आय",
    "income_per_category": "विभाग आय",
    "total_expense": "कुल व्यय",
    "expense_per_category": "विभाग व्यय",
    "net_profit": "नेट लाभ",
    "net_loss":"नेट हानि",
    "Milk Details":"दूध का विवरण",
    "Milk Sale":"दूध बिक्री",
    "Cattle Sale":"पशु बिक्री",
    "date_of_income": "आय की तारीख",
    "how_much_did_you_earn": "आपने कितना कमाया (₹ में)",
    "select_income_type": "आय का प्रकार चुनें",
    "enter_category": "वर्ग दर्ज करें",
    "new_income": "नई आय",
    "Other":"अन्य",
    'Select Buyer':'क्रेता का चयन करें',
    'Nutritional Feed Alert':'पोषण आहार चेतावनी',
    'provide': 'प्रदान करें',
    'nutritional': 'पोषणयुक्त',
    // 'feed': 'चारा',
    'with': 'के साथ',
  // "Nutritional Feed Alert": "पोषण चारा अलर्ट",
  "Dry Alert": "सूखा चक्र अलर्ट",
  "Heat Alert": "गर्मी का अलर्ट",
  "Pregnancy Test Alert": "गर्भावस्था परीक्षण अलर्ट",
  "Calving Alert": "बच्चे के जन्म का अलर्ट",
  "Milking Alert": "दूध दुहाई का अलर्ट",
  "AI Alert": "कृत्रिम गर्भाधान अलर्ट",
  "Deworming Vaccine Alert": "कीड़ों की दवाइयों का टीका अलर्ट",
  "Brucellosis Vaccine Alert": "ब्रूसलोसिस टीका अलर्ट",
  "Modified Theileriosis Vaccine Alert": "संशोधित थिलेरियोसिस टीका अलर्ट",
    'high': 'उच्च',
    'protein': 'प्रोटीन',
  // "provide": "प्रदान करें",
  // "nutritional": "पोषक",
  // "feed": "चारा",
  // "with": "के साथ",
  // "high": "उच्च",
  // "protein": "प्रोटीन",
  "and": "और",
  "fibre": "फाइबर",
  "content": "सामग्री",

  "is": "है",
  "expected": "की संभावना है",
  "to": "के लिए",
  "go": "जाना",
  // "dry": "सूखा",

  "heat": "गर्मी",
  "for": "के लिए",
  "cattle": "पशु",

  "pregnancy": "गर्भावस्था",
  "test": "परीक्षण",
  "alert": "अलर्ट",

  "due": "के लिए समय आ गया है",
  "calving": "बच्चे का जन्म",
  "milking": "दूध दुहाई",
  "ready": "तैयार",
  // "insemination": "गर्भाधान",

  "deworming": "कीड़े मारने",
  // "vaccination": "टीकाकरण",

  "brucellosis": "ब्रूसलोसिस",

  "modified": "संशोधित",
  "theileriosis": "थिलेरियोसिस",
    // 'and': 'और',
    // 'fibre': 'रेशा',
    // 'content': 'सामग्री',
  "provide nutritional feed with high protein and fibre content": "उच्च प्रोटीन और फाइबर सामग्री वाला पोषक चारा प्रदान करें", // Nutritional alert
  "is expected to go dry": "सूखा होने की संभावना है", // Dry alert
  "Heat alert": "गर्मी का अलर्ट", // Heat alert for cattle
  "is due for pregnancy test": "गर्भावस्था परीक्षण के लिए समय आ गया है", // Pregnancy Test alert
  "is due for calving": "बच्चे के जन्म का समय आ गया है", // Calving alert
  "is ready for milking": "दूध दुहाई के लिए तैयार है", // Milking alert after calving
  "is due for Insemination": "कृत्रिम गर्भाधान के लिए समय आ गया है", // Artificial Insemination alert for Heifers
  "is due for deworming vaccination": "कीड़े मारने के टीके का समय आ गया है", // Deworming vaccination alert
  "is due for brucellosis vaccination": "ब्रूसलोसिस के टीके का समय आ गया है", // Brucellosis vaccination alert
  "is due for modified theileriosis vaccination": "संशोधित थिलेरियोसिस के टीके का समय आ गया है", // Modified Theileriosis vaccination alert
    // 'provide nutritional feed with high protein and fibre content':'उच्च प्रोटीन और फाइबर सामग्री वाला पोषणयुक्त आहार प्रदान करें',
    'Fat Percentage':'वसा प्रतिशत',
    'SNF Percentage':'एसएनएफ प्रतिशत',
    'Quantity (Liters)':'मात्रा (लीटर में)',
    "new_expense": "नया व्यय",
    "date_of_expense": "व्यय की तारीख",
    "how_much_did_you_spend": "आपने कितना व्यय किया (₹ में)",
    "select_expense_type": "व्यय का प्रकार चुनें",
    "edit_income": "आय संपादित करें",
    "edit_expense": "व्यय संपादित करें",
    "income_category": "आय वर्ग",
    "expense_category": "व्यय वर्ग",
    "transaction_date": "लेन-देन की तारीख",
    "enter_transaction_amount": "लेन-देन राशि दर्ज करें",
    "delete": "हटाएं",
    "save": "सहेजें",
    "expiry_date": "समाप्ति तिथि",
    "current_stock": "वर्तमान भंडार",
    "current_need": "वर्तमान आवश्यकता",
    "add_feed_item": "चारा आइटम जोड़ें",
    "item_name": "आइटम का नाम",
    "quantity": "मात्रा",
    "required_quantity": "आवश्यक मात्रा",
    "category": "श्रेणी",
    "edit_feed_item": "चारा आइटम संपादित करें",
    "need": "आवश्यकता",
    "stock": "स्टॉक",
    'Born on Farm':'खेत में जन्मा',
    'Purchased':'खरीदा गया',
    "new_cattle_added_successfully": "नई पशु सफलतापूर्वक जोड़ा गया",
    'notifications': "सूचनाएं"
  };
}
