class LocalizationEn {
  static const Map<String, String> translations = {
    'Cow': 'Cow',
    'Buffalo': 'Buffalo',
    'calve': 'Calve',
    'Type': 'Type',
    'Register a New Farm': 'Register a New Farm',
    'Phone Number': 'Phone Number',
    'Sign Up': 'Sign Up',
    'Enter Your Phone Number': 'Enter Your Phone Number',
    'Login To Dairy Sangrah': 'Login To Dairy Sangrah',
    "Didn't receive code": "Didn't receive code",
    'Resend OTP': 'Resend OTP',
    'Continue': 'Continue',
    'Enter OTP': 'Enter OTP',
    'cattles': 'Cattles',
    'feed': 'Feed',
    'Calf': 'Calf',
    'ai': 'Ai',
    'transaction': 'Transaction',
    'avg_milk': 'Avg Milk',
    'dry_cows': 'Dry Cows',
    'RF ID': "RF Id",
    "breed": 'Breed',
    "sex": "Sex",
    'new_cattle': 'New Cattle',
    'enter_the_rfid': 'Enter the RFID',
    'gender': 'Gender',
    'enter_the_DOB': 'Enter the Date of Birth',
    'enter_the_weight': 'Enter the Weight',
    'source_of_cattle': 'Source of Cattle',
    'enter_the_breed': 'Enter the breed',
    'status': 'Status',
    'isPregnant': 'Is Pregnant',
    'no': 'No',
    'yes': 'Yes',
    'male': 'Male',
    'female': 'Female',
    'born on farm': 'Born on Farm',
    'purchased': 'Purchased',
    'Milked': 'Milked',
    'Heifer': 'Heifer',
    'insemination': 'Insemination',
    "semen sale": "semen sale",
    'abortion': 'Abortion',
    'Dry': 'Dry',
    'dry': 'Dry',
    'calved': 'Calved',
    'pregnant': 'Pregnant',
    'submit': 'Submit',
    'search_cattle': 'Search Cattle',
    'state': 'State',
    'all': 'All',
    'sahiwal': 'Sahiwal',
    'gir': 'Gir',
    'jersey': 'Jersey',
    'holstein': 'Holstein',
    'filter_options': 'Filter Options',
    'confirm_filters': 'Confirm Filters',
    'clear_filters': 'Clear Filters',
    'vaccination': 'Vaccination',
    'please_wait': 'Please wait ...',
    'events': "Events",
    'add_event': "Add Event",
    'details': "Details",
    "age": "Age",
    "dob": "DOB",
    "weight": "Weight",
    "milk_records": "Milk Records",
    "date": "Date",
    "total_milk": "Total Milk:",
    "litre": "L",
    "Litres": "Litres",
    "add_milk_data": "Add Milk Data",
    "select_rfid": "Select RFID",
    "morning_milk": "Morning Milk",
    "evening_milk": "Evening Milk",
    "milking_date": "Milking Date",
    "Source": "Source",
    //"green_fodder": "Green Fodder",
    //"dry_fodder": "Dry Fodder",
    //"concentrate": "Concentrate",
    "add": "Add",
    "please_select_rfid": "Please select RFID",
    "please_enter_value": "Please enter a value",
    "please_choose_date": "Please choose a date",
    "morning": "Morning",
    "evening": "Evening",
    "total": "Total",
    "transactions": "Transactions",
    "Milk Sale": "Milk Sale",
    "cattle_sale": "Cattle Sale",
    "other": "Other",
    "income": "Income",
    "expenses": "Expenses",
    "amount": "Amount",
    "on_date": "On Date",
    "Maize": "Maize",
    "Barley": "Barley",
    "Mustard": "Mustard",
    "Rye Grass": "Rye Grass",
    "Bajra": "Bajra",
    "Sorghum": "Sorghum",
    "Barseem": "Barseem",
    "Oats": "Oats",
    "Others": "Others",
    "Feed": "Feed",
    "Animals": "Animals",
    "Green Fodder": "Green Fodder",
    "Dry Fodder": "Dry Fodder",
    "Concentrate": "Concentrate",
    "Total Count": "Total Count",
    "Inventory": "Inventory",
    "own farm": "Own Farm",
    "Veterinary": "Veterinary",
    "Labor Costs": "Labor Costs",
    "Equipment and Machinery": "Equipment and Machinery",
    "total_transactions": "Total Transactions",
    "date_range": "Date range:",
    "total_income": "Total Income",
    "income_per_category": "Income per Category",
    "total_expense": "Total Expense",
    "expense_per_category": "Expense per Category",
    "net_profit": "Net Profit",
    "net_loss": "Net Loss",
    "Cattle Sale": "Cattle Sale",
    'Calculate': 'Calculate',
    'Save': 'Save',
    "Get started with your farm management journey": "Get started with your farm management journey",
    "date_of_income": "Date of Income",
    "Dairy Sangrah Registration": "Dairy Sangrah Registration",
    "Join an Existing Farm": "Join an Existing Farm",
    'Confirm': 'Confirm',
    "how_much_did_you_earn": "How much did you earn (in ₹)",
    "select_income_type": "Select Income type",
    "enter_category": "Enter Category",
    "new_income": "New Income",
    "new_expense": "New Expense",
    'Rate per Unit': 'Rate per Unit',
    'Quantity': 'Quantity',
    'Total Price': 'Total Price',
    'Quantity/Yield': "Quantity/Yield",
    "Other": "Other",
    "date_of_expense": "Date of expense",
    "how_much_did_you_spend": "How much did you spend (in ₹)",
    "select_expense_type": "Select Expense type",
    "edit_income": "Edit Income",
    "edit_expense": "Edit Expense",
    "income_category": "Income Category",
    "expense_category": "Expense Category",
    "transaction_date": "Transaction Date",
    "enter_transaction_amount": "Enter Transaction Amount",
    "delete": "Delete",
    "save": "Save",
    "expiry_date": "Expiry Date",
    "current_stock": "Current Stock",
    "current_need": "Current Need",
    "add_feed_item": "Add Feed Item",
    "item_name": "Item Name",
    "quantity": "Quantity",
    "required_quantity": "Required Quantity",
    "category": "Category",
    "edit_feed_item": "Edit Feed Item",
    'Enter Custom Purchased Type': 'Enter Custom Purchased Type',
    'Enter Custom Homemade Type': 'Enter Custom Homemade Type',
    'Enter its cost': 'Enter its cost',
    'De-Oiled Rice Bran': 'De-Oiled Rice Bran',
    'Soyabean': 'Soyabean',
    'Wheat Bran': 'Wheat Bran',
    'DCP': 'DCP',
    'LSP': 'LSP',
    'Salt': 'Salt',
    'Sodium Bicarbonate': 'Sodium Bicarbonate',
    'Nicen': 'Nicen',
    'Urea': 'Urea',
    'Mineral Mixture': 'Mineral Mixture',
    'Custom Type cannot be empty!': 'Custom Type cannot be empty!',
    'Select Ingredients:': 'Select Ingredients:',
    "need": "Need",
    "stock": "Stock",
    'homemade': 'Homemade',
    'new_cattle_added_successfully': "New Cattle Added Successfully!!",
    'notifications': "Notifications",
    'No existing Farm!': 'No existing Farm!',
    'Not Registered Content': 'There is no farm registered with this number.Please choose REGISTER to register as a new Farm or choose CANCEL to go back!',
    'register': 'Register',
    'cancel': 'Cancel',
    'Owner Name': 'Owner Name',
    'Phone No.': 'Phone No.',
    'Farm Name': 'Farm Name',
    'Farm Address': 'Farm Address',
    'Profile': 'Profile',
    'Log out': 'Log out',
    'Delete Data': 'Delete Data',
    "Are you Sure?": "Are you Sure?",
    'Delete Data Content': 'This will delete all the farm data permanently but the farm still remains registered. Please choose YES to continue and CANCEL to go back!',
    'Delete Account': 'Delete Account',
    'Delete Account Content': "This will delete all the user and farm data permanently. Please choose DELETE to continue and CANCEL to go back!",
    're-login': 'Re-Login',
    'requires recent login':'This action requires recent login!',
    're_login content':'Please choose Re-LOGIN and try again or choose CANCEL to go back!',
    'More Options': 'More Options',
    'Edit Profile': 'Edit Profile',
    'Error in Fetch': 'Error in Fetch',
    'Save Changes': 'Save Changes',
    'Deleted': 'Deleted',
    'edit_details': 'Edit Details',
    'please_select_gender': 'Please select gender',
    'please_select_source': 'Please select source',
    'please_enter_breed': 'Please enter breed',
    'cattle_details_updated_successfully': 'Cattle details updated Successfully!!',
    'event_name': 'Event Name',
    'event_date': 'Event Date',
    'please_select_event_and_date': 'Please select an event and date',
    'rfid_already_exists': 'RFID already exists',
    'please_enter_tag_num':'Please enter tag number',
    'please_select_cattle_type': 'Please select type of cattle',
    'list_is_empty': 'The list is empty!',
    'no_entries_for_sel_date': 'No entries found for selected date!',
    'edit_milk_data': 'Edit Milk Data',
    'enter_valid_num': 'Please enter a valid number',
    'add_transaction': 'Add Transaction',
    'no_matching_price': 'No matching price found for',
    'fat': 'Fat',
    'snf': 'SNF',
    'err_msg': 'Error Message',
    'OK': 'OK',
    'please_sel_income_type': 'Please select an income type',
    'please_enter_category_other': "Please enter a category for 'Other' income type",
    'please_sel_milk_buyer': 'Please select a milk buyer',
    'please_sel_fat_snf_qty': 'Please enter Fat, SNF, and Quantity values',
    'fat_snf_qty_val_chk': 'Fat, SNF, and Quantity must be valid numbers greater than zero',
    'no_price_fat_snf': 'Milk price data not found for the given Fat and SNF',
    'please_enter_tot_income': 'Please enter the total income',
    'sel_feed_consumption': 'Select Feed Consumption :',
    'out_of_stock': 'Out of Stock, please refill!',
    'enter_qty_consumed_kg': 'Enter qty consumed in Kg',
    'cannot_be_more_than_existing': 'cannot be more than existing quantity!',
    'Kg': 'Kg',
    'Quintal': 'Quintal',
    "amul": "Amul",
    "verka": "Verka",
    "nestle": "Nestle",
    "d to c": "D to C",
    'start': 'Start',
    'end': 'End',
    'Rate': 'Rate',
  };
}
