class LocalizationTe {
  static const Map<String, String> translations = {
    "cattles": "పశువులు",
    "Register a New Farm": "కొత్త పాడి పరిశ్రమ నమోదు చేయండి",
    "feed": "మేత",
    "Cow": "ఆవు",
    "Buffalo": "గేదె",
    "transaction": "లావాదేవీ",
    "avg_milk": "సగటు పాలు",
    "dry_cows": "ఒట్టి ఆవులు",
    "RF ID": "ఆర్ ఎఫ్ ఐడి",
    "Search Cattle": "పశువులను వెతకండి",
    "breed": "జాతి",
    "sex": "లింగం",
    "new_cattle": "కొత్త పశువులు",
    "enter_the_rfid": "ఆర్ ఎఫ్ ఐడి నమోదు చేయండి",
    "gender": "లింగం",
    "enter_the_DOB": "జనన తేది నమోదు చేయండి",
    "enter_the_weight": "బరువు నమోదు చేయండి",
    "source_of_cattle": "పశువుల మూలం",
    "select_the_breed": "జాతి ఎంచుకోండి",
    "status": "స్థితి",
    "isPregnant": "గర్భవతి",
    "no": "కాదు",
    "yes": "అవును",
    "male": "మగ",
    "female": "ఆడ",
    "born on farm": "పాడి పరిశ్రమలో పుట్టింది",
    "purchased": "కొనుగోలు చేయబడింది",
    "Select Ingredients:": "సామగ్రి ఎంచుకోండి:",
    "Milked": "పాలు ఇస్తున్న",
    "milked": "పాలు ఇస్తున్న",
    "Heifer": "లేగదూడ",
    "insemination": "గర్భధారణ",
    "abortion": "గర్భపాతం",
    "Dry": "పాలు నిలిపిన",
    "dry": "పాలు నిలిపిన",
    "calf": "దూడ",
    "Calf": "దూడ",
    "Animals": "జంతువులు",
    "Green Fodder": "పచ్చి మేత",
    "Dry Fodder": "ఎండు మేత",
    "Concentrate": "పశువుల దాణా",
    "unknown_item": "తెలియని వస్తువులు",
    "Enter custom type": "దయచేసి రకం నమోదు చేయండి",
    "quantity": "పరిమాణం",
    "Quantity": "పరిమాణం",
    "Wheat Straw": "గోధుమ గడ్డి",
    "Paddy Straw": "వరి గడ్డి",
    "Enter Custom Purchased Type": "కస్టమ్ కొనుగోలు రకం నమోదు చేయండి",
    "Enter Custom Homemade Type": "కస్టమ్ ఇంటి తయారీ రకం నమోదు చేయండి",
    "Enter its cost": "దాని ఖరీదు నమోదు చేయండి",
    "Custom Type cannot be empty!": "కస్టమ్ రకం ఖాళీ ఉండకూడదు!",
    "Mustard": "ఆవాలు",
    "Maize": "మొక్కజొన్న",
    "Barley": "బార్లీ",
    "De-Oiled Rice Bran": "నూనె తీసిన తవుడు",
    "Soyabean": "సోయాబీన్స్",
    "Wheat Bran": "గోధుమ తవుడు",
    "DCP": "డీసీపీ",
    "LSP": "ఎల్ఎస్పీ",
    "Salt": "ఉప్పు",
    "Sodium Bicarbonate": "సోడియం బైకార్బోనేట్",
    "Nicen": "నైసెన్",
    "Urea": "యూరియా",
    "Mineral Mixture": "ఖనిజ మిశ్రమం",
    "Others": "ఇతరులు",
    "homemade": "ఇంటి లో చేసినది",
    "Rate": "రేటు",
    "date": "తేది",
    "Source": "మూలం",
    "own farm": "స్వంత ఫారం",
    "Quantity/Yield": "పరిమాణం / ఉత్పత్తి",
    "Rate per Unit": " ప్రతి యూనిట్ రేటు",
    "Total Price": "మొత్తం ధర",
    "Land Area(in acres)": "భూమి కొలత(ఎకరాల్లో)",
    "Seed Cost": "విత్తన ఖరీదు",
    "Fertilizers Cost": "ఎరువుల ఖరీదు",
    "Inoculants Cost": "ఇనోకులెంట్స్ ఖరీదు",
    "Labor Cost": "కూలీ ఖర్చు",
    "Diesel Cost": "డీజిల్ ఖర్చు",
    "Total Production Cost": "మొత్తం ఉత్పత్తి ఖర్చు",
    "Calculate": "గణించు",
    "Save": "సేవ్ చేయండి",
    "calved": "బిడ్డ పుట్టింది",
    "pregnant": "గర్భవతి",
    "submit": "సమర్పించు",
    "search_cattle": "పశువులను వెతకండి",
    "state": "స్థితి",
    "sahiwal": "సాహివాల్",
    "gir": "గిర్",
    "jersey": "జర్సీ",
    "holstein": "హోల్స్టీన్",
    "Rye Grass": "రై గడ్డి",
    "Bajra": "సజ్జలు",
    "Sorghum": "జొన్నలు",
    "Berseem": "బెర్సీమ్",
    "Oats": "ఓట్స్",
    "all": "అన్ని",
    "filter_options": "ఫిల్టర్ ఎంపికలు",
    "confirm_filters": "ఫిల్టర్ నిర్ధారించు",
    "clear_filters": "ఫిల్టర్ తొలగించు",
    "vaccination": "టీకాకరణ",
    "please_wait": "దయచేసి వేచి ఉండండి ...",
    "events": "ఈవెంట్లు",
    "add_event": "ఈవెంట్ జోడించు",
    "details": "వివరాలు",
    "age": "వయస్సు",
    "dob": "పుట్టిన తేది",
    "weight": "బరువు",
    "Total Count": "మొత్తం సంఖ్య",
    "Total Income": "మొత్తం ఆదాయం",
    "semen sale": "వీర్య విక్రయం",
    "milk_records": "పాల రికార్డులు",
    "Total Milk": "మొత్తం పాలు",
    "litre": "లీటరు",
    "Litres": "లీటర్లు",
    "add_milk_data": "పాల డేటా జోడించు",
    "select_rfid": "ఆర్ ఎఫ్ ఐడి ఎంచుకోండి",
    "morning_milk": "ఉదయం పాలు (లీటర్లు)",
    "evening_milk": "సాయంత్రం పాలు (లీటర్లు)",
    "milking_date": "పాలు తీసిన తేది",
    "add": "జోడించు",
    "please_select_rfid": "దయచేసి ఆర్ ఎఫ్ ఐడి ఎంచుకోండి",
    "please_enter_value": "దయచేసి విలువ నమోదు చేయండి",
    "please_choose_date": "దయచేసి తేది ఎంచుకోండి",
    "morning": "ఉదయం",
    "evening": "సాయంత్రం",
    "total": "మొత్తం",
    "milk_sale": "పాల విక్రయం",
    "cattle_sale": "పశు విక్రయం",
    "other": "ఇతర",
    "income": "ఆదాయం",
    "expenses": "ఖర్చులు",
    "transactions": "లావాదేవీలు",
    "amount": "మొత్తం",
    "on_date": "తేదీ",
    "Feed": "మేత",
    "Inventory": "జాబితా",
    "Veterinary": "పశు వైద్యము",
    "Labor Costs": "కూలీ ఖర్చులు",
    "Equipment and Machinery": "పరికరాలు మరియు యంత్రాలు",
    "total_transactions": "మొత్తం లావాదేవీలు",
    "date_range": "తేదీ పరిధి",
    "total_income": "మొత్తం ఆదాయం",
    "income_per_category": "విభాగాల వారీగా ఆదాయం",
    "total_expense": "మొత్తం ఖర్చు",
    "expense_per_category": "విభాగాల వారీగా ఖర్చు",
    "net_profit": "నికర లాభం",
    "net_loss": "నికర నష్టము",
    "Milk Details": "పాల వివరాలు",
    "Milk Sale": "పాల విక్రయం",
    "Cattle Sale": "పశు విక్రయం",
    "date_of_income": "ఆదాయ తేది",
    "how_much_did_you_earn": "మీరు ఎంత సంపాదించారో (₹లో)",
    "select_income_type": "ఆదాయ రకం ఎంచుకోండి",
    "enter_category": "విభాగం నమోదు చేయండి",
    "new_income": "కొత్త ఆదాయం",
    "Other": "ఇతర",
    "Select Buyer": "కొనుగోలు దారును ఎంచుకోండి",
    "Nutritional Feed Alert": "పోషకాహారం హెచ్చరిక",
    "Dry Alert": "పాలు నిలుపు హెచ్చరిక",
    "Heat Alert": "యెద హెచ్చరిక",
    "Pregnancy Test Alert": "గర్భధారణ పరీక్ష హెచ్చరిక",
    "Calving Alert": "ప్రసూతి హెచ్చరిక",
    "Milking Alert": "పాలు పితికే హెచ్చరిక",
    "AI Alert": "కృత్రిమ గర్భధారణ హెచ్చరిక",
    "Deworming Vax Alert": "నులిపురుగుల నివారణ టీకా హెచ్చరిక",
    "Brucellosis Vax Alert": "బ్రూసెలోసిస్ టీకా హెచ్చరిక",
    "Modified Theileriosis Vax Alert": "మోడిఫైడ్ థైలీరియోసిస్ టీకా హెచ్చరిక",
    "Dairy Sangrah Registration": "డెయిరీ సంగ్రహ్ నమోదు",
    "Get into Existing Farm": "ఉన్న పాడి పరిశ్రమలో ప్రవేశించండి",
    "Get started with your farm management journey": "మీ పాడి పరిశ్రమ నిర్వహణ ప్రయాణాన్ని ప్రారంభించండి",
    "Confirm": "నిర్ధారించు",
    "Sign Up": "నమోదు చేయండి",
    "Enter Your Phone Number": "మీ ఫోన్ నంబర్ నమోదు చేయండి",
    "Phone Number": "ఫోన్ నంబర్",
    "Login To Dairy Sangrah": "డెయిరీ సంగ్రహ్ లో లాగిన్ అవ్వండి",
    "Didn't receive code?": "కోడ్ రాలేదు?",
    "Resend OTP": "OTP మళ్లీ పంపు",
    "Continue": "కొనసాగించు",
    "Enter OTP": "OTP నమోదు చేయండి",
    "provide nutritional feed with high protein and fibre content": "ఎక్కువ ప్రోటీన్ మరియు ఫైబర్ కలిగిన పోషక మేతను ఇవ్వండి",
    "is expected to go dry": "పాలు నిలుపు సమయం వచ్చింది",
    "Heat alert": "యెద హెచ్చరిక",
    "is due for pregnancy test": "గర్భధారణ పరీక్షకు సమయం వచ్చింది",
    "is due for calving": "ప్రసవ సమయం వచ్చింది",
    "is ready for milking": "పాలు తీయడానికి సిద్ధంగా ఉంది",
    "is due for Insemination": "గర్భధారణకు సమయం వచ్చింది",
    "is due for deworming vaccination": "నులిపురుగుల నివారణ టీకా సమయం వచ్చింది",
    "is due for brucellosis vaccination": "బ్రూసెలోసిస్ టీకా సమయం వచ్చింది",
    "is due for modified theileriosis vaccination": "మోడిఫైడ్ థైలీరియోసిస్ టీకా సమయం వచ్చింది",
    "Fat Percentage": "కొవ్వు శాతం",
    "SNF Percentage": "SNF శాతం",
    "Quantity (Liters)": "పరిమాణం (లీటర్లు)",
    "new_expense": "కొత్త ఖర్చు",
    "date_of_expense": "ఖర్చు తేది",
    "how_much_did_you_spend": "మీరు ఎంత ఖర్చు చేసారు (₹లో)",
    "select_expense_type": "ఖర్చు రకం ఎంచుకోండి",
    "edit_income": "ఆదాయం సవరించు",
    "edit_expense": "ఖర్చు సవరించు",
    "income_category": "ఆదాయ వర్గం",
    "expense_category": "ఖర్చు వర్గం",
    "transaction_date": "లావాదేవీ తేది",
    "enter_transaction_amount": "లావాదేవీ మొత్తాన్ని నమోదు చేయండి",
    "delete": "తొలగించు",
    "save": "సేవ్ చేయండి",
    "Type": "రకం",
    "expiry_date": "గడువు తేది",
    "current_stock": "ప్రస్తుత స్టాక్",
    "current_need": "ప్రస్తుత అవసరం",
    "add_feed_item": "మేత అంశం జోడించు",
    "item_name": "అంశం పేరు",
    "required_quantity": "అవసరమైన పరిమాణం",
    "category": "వర్గం",
    "edit_feed_item": "మేత అంశం సవరించు",
    "need": "ఆవశ్యకం",
    "stock": "స్టాక్",
    "new_cattle_added_successfully": "కొత్త పశువుల విజయవంతంగా జోడించబడింది",
    "notifications": "అధిసూచనలు",
    "No existing Farm!": "పాడి పరిశ్రమ నమోదు చేసి లేదు!",
    "Not Registered Content": "ఈ నంబర్ తో పాడి పరిశ్రమ నమోదు చేసి లేదు. దయచేసి కొత్త పాడి పరిశ్రమ నమోదు చేయడానికి 'నమోదు' ఎంచుకోండి లేదా వెనక్కి వెళ్లడానికి 'రద్దు' ఎంచుకోండి!",
    "register": "నమోదు చేయండి",
    "cancel": "రద్దు చేయండి",
    "Owner Name": "యజమాని పేరు",
    "Phone No.": "ఫోన్ నంబర్",
    "Farm Name": "పాడి పరిశ్రమ పేరు",
    "Farm Address": "పాడి పరిశ్రమ చిరునామా",
    "Profile": "ప్రొఫైల్ - వ్యక్తిగత వివరాలు",
    "Log out": "లాగ్ అవుట్ చేయండి",
    "Delete Data": "డేటాను తొలగించండి",
    "Are you Sure?": "మీరు నిశ్చయంగా ఉన్నారా?",
    "Delete Data Content": "ఈ చర్యతో ఫార్మ్ డేటా పూర్తిగా తొలగించబడుతుంది, కానీ ఫార్మ్ నమోదు కొనసాగుతుంది. ముందుకు వెళ్లడానికి 'అవును' ఎంచుకోండి లేదా తిరిగి వెళ్లడానికి 'రద్దు' ఎంచుకోండి!",
    "Delete Account": "ఖాతాను తొలగించండి",
    "Delete Account Content": "ఈ చర్యతో మీ యూజర్ మరియు ఫార్మ్ డేటా మొత్తం పూర్తిగా తొలగించబడుతుంది. ముందుకు వెళ్లడానికి 'తొలగించు' ఎంచుకోండి లేదా తిరిగి వెళ్లడానికి 'రద్దు' ఎంచుకోండి!",
    "re-login": "మళ్లీ లాగిన్ అవ్వండి",
    "requires recent login": "ఇటీవల లాగిన్ కావడం అవసరం!",
    "re_login content": "దయచేసి 'మళ్లీ లాగిన్ అవ్వండి' ఎంచుకుని మళ్లీ ప్రయత్నించండి, లేదా తిరిగి వెళ్లడానికి 'రద్దు' ఎంచుకోండి!",
    "More Options": "మరిన్ని ఎంపికలు",
    "Edit Profile": "ప్రొఫైల్ సవరించండి",
    "Error in Fetch": "డేటా తీసుకోవడంలో లోపం",
    "Save Changes": "మార్పులను సేవ్ చేయండి",
    "Deleted": "తొలగించబడింది",
    "edit_details": "వివరాలు సవరించు",
    "please_select_gender": "దయచేసి లింగాన్ని ఎంచుకోండి",
    "please_select_source": "దయచేసి మూలాన్ని ఎంచుకోండి",
    "please_select_breed": "దయచేసి జాతిని ఎంచుకోండి",
    "cattle_details_updated_successfully": "వివరాలు విజయవంతంగా నవీకరించబడ్డాయి!",
    "event_name": "ఈవెంట్ పేరు",
    "event_date": "ఈవెంట్ తేదీ",
    "please_select_event_and_date": "దయచేసి ఈవెంట్ మరియు తేదీని ఎంచుకోండి",
    "rfid_already_exists": "ఆర్‌ఎఫ్‌ఐడీ ముందే ఉంది",
    "please_enter_tag_num": "దయచేసి ట్యాగ్ నెంబర్ నమోదు చేయండి",
    "please_select_cattle_type": "దయచేసి పశువుల రకాన్ని ఎంచుకోండి",
    "list_is_empty": "జాబితా ఖాళీగా ఉంది",
    "no_entries_for_sel_date": "ఎంచుకున్న తేదీకి ఎంట్రీలు లేవు!",
    "edit_milk_data": "పాల డేటా సవరించండి",
    "enter_valid_num": "సరైన సంఖ్యను నమోదు చేయండి",
    "add_transaction": "లావాదేవీ చేర్చు",
    "no_matching_price": "తగిన ధర కనుగొనబడలేదు -",
    "fat": "కొవ్వు",
    "snf": "SNF",
    "err_msg": "లోపపు సందేశం",
    "OK": "సరే",
    "please_sel_income_type": "దయచేసి ఆదాయ రకాన్ని ఎంచుకోండి",
    "please_enter_category_other": "'ఇతర' ఆదాయ రకం కోసం దయచేసి వర్గం నమోదు చేయండి",
    "please_sel_milk_buyer": "దయచేసి పాల కొనుగోలుదారుని ఎంచుకోండి",
    "please_sel_fat_snf_qty": "దయచేసి కొవ్వు, SNF మరియు పరిమాణం విలువలను నమోదు చేయండి",
    "fat_snf_qty_val_chk": "కొవ్వు, SNF, మరియు పరిమాణం విలువలు శూన్యంకంటే ఎక్కువ ఉండాలి",
    "no_price_fat_snf": "ఇచ్చిన కొవ్వు మరియు SNF కొరకు పాల ధర డేటా కనుగొనబడలేదు",
    "please_enter_tot_income": "దయచేసి మొత్తం ఆదాయాన్ని నమోదు చేయండి",
    "sel_feed_consumption": "మేతకు ఉపయోగించిన పరిమాణాన్ని ఎంచుకోండి:",
    "out_of_stock": "స్టాక్ అయిపోయింది, దయచేసి రీఫిల్ చేయండి!",
    "enter_qty_consumed_kg": "వినియోగించిన పరిమాణం (కిలోలలో) నమోదు చేయండి",
    "cannot_be_more_than_existing": "ఇది ఉన్న పరిమాణం కంటే ఎక్కువ ఉండకూడదు!",
    "Unit": "యూనిట్",
    "Kg": "కిలో",
    "Quintal": "క్వింటాల్",
    "amul": "అమూల్",
    "verka": "వెర్కా",
    "nestle": "నెస్ట్‌లే",
    "d to c": "నేరుగా వినియోగదారుడికి",
    "start": "ఆరంభం",
    "end": "ముగింపు",
    "data_del_msg": "దయచేసి వేచి ఉండండి, డేటా తొలగిస్తున్నాం!",
    "Land Area (in acres)": "భూమి పరిమాణం (ఎకరాలలో)",
    "app_version": "యాప్ సంస్కరణ",
    "Select Language": "భాష ఎంచుకోండి",
    "English": "ఇంగ్లీష్",
    "Hindi": "హిందీ",
    "Punjabi": "పంజాబీ",
    "Telugu": "తెలుగు",
    "Preferred Language": "ప్రాధాన్య భాష"
  };
}