class LocalizationEn {
  static const Map<String, String> translations = {
    'Cows':'Cows',
    // 'cow':'Cow',
    'Cow':'Cow',
    'Buffalo':'Buffalo',
    'Buffalos':'Buffalos',
    'calve':'Calve',
    'Type':'Type',
    'Register a New Farm':'Register a New Farm',
    // 'Enter your phone number':'Enter your phone number',
    'Phone Number':'Phone Number',
    'Sign Up':'Sign Up',
    'Enter Your Phone Number':'Enter Your Phone Number',
    'Login To DairyMate':'Login To DairyMate',
    "Didn't receive code":"Didn't receive code",
    'Resend OTP':'Resend OTP',
    'Continue':'Continue',
    'Enter OTP':'Enter OTP',
    'cattles': 'Cattles',
    'feed': 'Feed',
    'Calf':'Calf',
    'ai':'Ai',
    'transaction': 'Transaction',
    'avg_milk': 'Avg Milk',
    'dry_cows': 'Dry Cows',
    'rf_id':"RF Id",
    "breed":'BREED',
    "sex":"SEX",
    'new_cattle':'New Cattle',
    'enter_the_rfid':'Enter the RFID',
    // 'Enter Your Phone Number':'Enter Your Phone Number',
    'gender':'Gender',
    'enter_the_DOB':'Enter the Date of Birth',
    'enter_the_weight':'Enter the Weight',
    'source_of_cattle':'Source of Cattle',
    'enter_the_breed':'Enter the breed',
    'status':'Status',
    'isPregnant': 'Is Pregnant',
    'no': 'No',
    'yes': 'Yes',
    'male':'Male',
    'female':'Female',
    'born_on_farm':'Born on Farm',
    'purchased':'Purchased',
    'Milked':'Milked',
    'Heifer':'Heifer',
    'insemination':'Insemination',
    "semen sale":"semen sale",
    'abortion':'Abortion',
    'Dry':'Dry',
    'calved':'Calved',
    'pregnant':'Pregnant',
    'submit':'Submit',
    'search_cattle':'Search Cattle',
    'state':'State',
    'filter_options':'Filter Options',
    'confirm_filters':'Confirm Filters',
    'clear_filters':'Clear Filters',
    'vaccination':'Vaccination',
    'please_wait':'Please wait ...',
    'events':"Events",
    'add_event':"Add Event",
    'details':"Details",
    "age":"Age",
    "dob":"DOB",
    "weight":"Weight",
    "milk_records":"Milk Records",
    "date":"Date",
    "total_milk":"Total Milk:",
    "litre":"L",
    "add_milk_data":"Add Milk Data",
    "select_rfid":"Select RFID",
    "morning_milk":"Morning Milk",
    "evening_milk":"Evening Milk",
    "milking_date":"Milking Date",
    "Green Fodder":"Green Fodder",
    "Dry Fodder":"Dry Fodder",
    "Concentrate":"Concentrate",
    "add":"Add",
    "please_select_rfid":"Please select RFID",
    "please_enter_value": "Please enter a value",
    "please_choose_date": "Please choose a date",
    "morning":"Morning",
    "evening":"Evening",
    "total":"Total",
    "transactions":"Transactions",
    "Milk Sale":"Milk Sale",
    "cattle_sale":"Cattle Sale",
    "other":"Other",
    "income":"Income",
    "expenses":"Expenses",
    "amount":"Amount",
    "on_date":"On Date",

    "Maize": "Maize",
    "Barley": "Barley",
    "Mustard": "Mustard",
    "Rye Grass": "Rye Grass",
    "Bajra": "Bajra",
    "Sorghum": "Sorghum",
    "Barseem": "Barseem",
    "Oats": "Oats",
    "Others": "Others",

    "Feed":"Feed",
    "Animals":"Animals",
    "Total Count":"Total Count",
    "Inventory":"Inventory",
    "Own Farm":"Own Farm",
    "Veterinary":"Veterinary",
    "Labor Costs":"Labor Costs",
    "Equipment and Machinery":"Equipment and Machinery",
    "total_transactions":"Total Transactions",
    "date_range":"Date range:",
    "total_income":"Total Income",
    "income_per_category":"Income per Category",
    "total_expense":"Total Expense",
    "expense_per_category":"Expense per Category",
    "net_profit":"Net Profit",
    "net_loss":"Net Loss",
    // "Milk Sale":"Milk Sale",
    "Cattle Sale":"Cattle Sale",
    'Calculate':'Calculate',
    'Save':'Save',
    "Get started with your farm management journey":  "Get started with your farm management journey",
    "date_of_income":"Date of Income",
    "DairyMate Registration":"DairyMate Registration",
    "Join an Existing Farm":"Join an Existing Farm",
    'Confirm':'Confirm',
    // 'Sign Up':'Sign Up',
    "how_much_did_you_earn":"How much did you earn (in ₹)",
    "select_income_type":"Select Income type",
    "enter_category":"Enter Category",
    "new_income":"New Income",
    "new_expense":"New Expense",
    'Rate per Unit':'Rate per Unit',
    'Quantity':'Quantity',
    'Total Price':'Total Price',
    'Quantity/Yield':"Quantity/Yield",
    "Other":"Other",
    "date_of_expense":"Date of expense",
    "how_much_did_you_spend":"How much did you spend (in ₹)",
    "select_expense_type":"Select Expense type",
    "edit_income": "Edit Income",
    "edit_expense": "Edit Expense",
    "income_category": "Income Category",
    "expense_category": "Expense Category",
    "transaction_date": "Transaction Date",
    "enter_transaction_amount": "Enter Transaction Amount",
    "delete":"Delete",
    "save":"Save",
    "expiry_date": "Expiry Date",
    "current_stock": "Current Stock",
    "current_need": "Current Need",
    "add_feed_item": "Add Feed Item",
    "item_name": "Item Name",
    "quantity": "Quantity",
    "required_quantity": "Required Quantity",
    "category": "Category",
    "edit_feed_item":"Edit Feed Item",
    'Enter Custom Purchased Type':'Enter Custom Purchased Type',
    'Enter Custom Homemade Type':'Enter Custom Homemade Type',
    'Enter its Cost':'Enter its cost',
    'Custom Type cannot be empty!':'Custom Type cannot be empty!',
    'Select Ingredients:':'Select Ingredients:',

    "need":"Need",
    "stock":"Stock",
    'Born on Farm':'Born on Farm',
    'Purchased':'Purchased',
    'new_cattle_added_successfully':"New Cattle Added Successfully!!",
    'notifications': "Notifications"
  };
}
