class LocalizationPun {
  static const Map<String, String> translations = {
    'cattles': 'ਪਸ਼ੂ',
    'feed': 'ਫੀਡ',
    'transaction': 'ਲੇਣ-ਦੇਣ',
    'avg_milk': 'ਔਸਤ ਦੁੱਧ',
    'dry_cows': 'ਸੂਕੀ ਗਾਏ',
    'rf_id':"ਆਰਐਫ ਆਈਡੀ",
    'Cows':'ਗਾਵਾਂ',
    'Buffalos':'ਮੱਝ',
    'Heifer':'ਵੈਯ੍ਰੀ',
    "Total Count":"ਕੁੱਲ ਗਿਣਤੀ",
    "semen sale":"ਵੀਰਜ ਦੀ ਵਿਕਰੀ",
    "Green Fodder":"ਹਰਾ ਚਾਰਾ",
    "Dry Fodder":"ਸੁੱਕਾ ਚਾਰਾi",
    "Concentrate":"ਕੇਂਦਰਿਤ",
    'breed':'ਨਸਲ',
    "sex": "ਲਿੰਗ",
    "new_cattle": "ਨਵੇਂ ਪਸ਼ੂ",
    "enter_the_rfid": "ਆਰਐਫਆਈਡੀ ਦਰਜ ਕਰੋ",
    "gender": "ਲਿੰਗ",
    "enter_the_DOB": "ਜਨਮ ਮਿਤੀ ਦਰਜ ਕਰੋ",
    "enter_the_weight": "ਵਜਨ ਦਰਜ ਕਰੋ",
    "source_of_cattle": "ਪਸ਼ੂਆਂ ਦਾ ਸੋਰਸ",
    "enter_the_breed": "ਨਸਲ ਦਰਜ ਕਰੋ",
    "status": "ਹਾਲਤ",
    'isPregnant': 'ਗਰਭਵਤੀ ਹੈ',
    "Animals":"ਜਾਨਵਰ",
    'no': 'ਨਹੀਂ',
    'yes': 'ਹਾਂ',
    "male": "ਨਰ",
    "female": "ਮਾਦਾ",
    'sahiwal':'ਸਾਹੀਵਾਲ',
    'All':'ਸਾਰੇ',
    'Gir':'ਗਿਰ',
    'Jersey':'ਜਰਸੀ',
    'Holstein':'ਹੋਲਸਟਾਈਨ',
    "born_on_farm": "ਖੇਤ 'ਚ ਪੈਦਾ ਹੋਇਆ",
    "purchased": "ਖਰੀਦਿਆ ਗਿਆ",
    "Milked": "ਦੁੱਧ ਦਿੱਤਾ",
    "Milk Details":"ਦੁੱਧ ਦੇ ਵੇਰਵੇ",
    "Hceifer": "ਬਛਿਆ",
    "insemination": "ਗਰਭਾਧਾਨ",
    "abortion": "ਗਰਭਪਾਤ",
    "Dry": "ਸੂਖਾ",
    "Calf":"ਵੱਛਾ",
    "calved": "ਵਾਛ ਬਈ ਗਾਈ",
    "pregnant":"ਗਰਭਵਤੀ",
    "submit": "ਪ੍ਰਸਤੁਤ",
    "search_cattle": "ਪਸ਼ੂ ਖੋਜੋ",
    "state": "ਹਾਲਤ",
    "filter_options": "ਫਿਲਟਰ ਚੋਣਾਂ",
    "confirm_filters": "ਫਿਲਟਰ ਪੁਸ਼ਟੀ ਕਰੋ",
    "clear_filters": "ਫਿਲਟਰ ਮਿਟਾਓ",
    'vaccination':'ਟੀਕਾ ਲਗਾਉਣਾ',
    'please_wait':'ਕਿਰਪਾ ਕਰਕੇ ਰੁਕੋ ...',
    'events':'ਘਟਨਾਵਾਂ',
    'add_event':"ਘਟਨਾਵਾਂ ਸ਼ਾਮਲ ਕਰੋ",
    'details':"ਵੇਰਵਾ",
    'age':"ਉਮਰ",
    "dob":"ਜਨਮ ਤਾਰੀਖ",
    "weight":"ਭਾਰ",
    "milk_records":"ਦੁੱਧ ਦਾ ਰਿਕਾਰਡ",
    "date":"ਤਾਰੀਖ਼",
    "total_milk":"ਕੁੱਲ ਦੁੱਧ:",
    "litre":"ਲੀ.",
    "add_milk_data":"ਦੁੱਧ ਦਾ ਡਾਟਾ ਸ਼ਾਮਲ ਕਰੋ",
    "select_rfid":" ਆਰਐਫ ਆਈਡੀ ਚੁਣੋ",
    "morning_milk":"ਸਵੇਰ ਦਾ ਦੁੱਧ",
    "evening_milk":"ਸ਼ਾਮ ਦਾ ਦੁੱਧ",
    "milking_date":"ਦੁੱਧ ਨਿਕਾਲਣ ਦੀ ਮਿਤੀ",
    "add":" ਸ਼ਾਮਲ ਕਰੋ",
    "please_select_rfid":" ਕਿਰਪਾ ਕਰਕੇ ਆਰਐਫ ਆਈਡੀ ਚੁਣੋ",
    "please_enter_value": "ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਮੁੱਲ ਦਾਖਲ ਕਰੋ",
    "please_choose_date": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਮਿਤੀ ਚੁਣੋ",
    "morning":"ਸਵੇਰ",
    "evening":"ਸ਼ਾਮ",
    "total":"ਕੁੱਲ",
    "milk_sale":"ਦੁੱਧ ਵੇਚਣ",
    "cattle_sale":"ਪਸੂ ਵੇਚਣ",
    "other":"ਹੋਰ",
    "income":"ਆਮਦਨ",
    "expenses":"ਖਰਚ",
    'transactions':"ਲੇਨ-ਦੇਨ",
    "amount":"ਰਕਮ",
    "on_date":" ਦਾਤ ਤੇ",
    "Feed": "ਚਾਰਾ",
    "Inventory" : "ਵਸਤੂ ਸੂਚੀ",

    "Maize": "ਮਕਕਾ",
    "Barley": "ਜੌ",
    "Mustard": "ਸਰੋਂ",
    "Rye Grass": "ਰਾਈ ਘਾਹ",
    "Bajra": "ਬਾਜਰਾ",
    "Sorghum": "ਜੁਆਰ",
    "Barseem": "ਬਰਸੀਮ",
    "Oats": "ਜਈ",
    "Others": "ਹੋਰ",


    "Veterinary": "ਪਸ਼ੂ ਚਿਕਿੱਤਸਾ",
    "Labor Costs": "ਮਜ਼ਦੂਰੀ ਖਰਚ",
    "Equipment and Machinery": "ਉਪਕਰਣ ਅਤੇ ਮਸ਼ੀਨਰੀ",
    "total_transactions": "ਕੁੱਲ ਲੇਨ-ਦੇਨ",
    "date_range": "ਮਿਤੀ ਦੀ ਸੀਮਾ:",
    "total_income": "ਕੁੱਲ ਆਮਦਨ",
    "income_per_category": "ਆਮਦਨ ਦਾ ਵਰਗ",
    "total_expense": "ਕੁੱਲ ਖਰਚ",
    "expense_per_category": "ਖਰਚ ਦਾ ਵਰਗ",
    "net_profit": "ਨੇਟ ਲਾਭ",
    "net_loss":"ਨੇਟ ਨੁਕਸਾਨ",
    "Milk Sale":"ੁੱਧ ਵੇਚਣ",
    "Cattle Sale":"ਪਸੂ ਵੇਚਣ",
    "date_of_income": "ਆਮਦਨ ਦੀ ਮਿਤੀ",
    "how_much_did_you_earn": "ਤੁਸੀਂ ਕਿੰਨਾ ਕਮਾਇਆ (₹ ਵਿੱਚ)",
    "select_income_type": "ਆਮਦਨ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    "enter_category": "ਵਰਗ ਦਾਖਲ ਕਰੋ",
    "new_income": "ਨਵੀਂ ਆਮਦਨ",
    "Other":"ਹੋਰ",
    "new_expense": "ਨਵਾਂ ਖਰਚ",
    "date_of_expense": "ਖਰਚ ਦੀ ਮਿਤੀ",
    "how_much_did_you_spend": "ਤੁਸੀਂ ਕਿੰਨਾ ਖਰਚ ਕੀਤਾ (₹ ਵਿੱਚ)",
    "select_expense_type": "ਖਰਚ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    "edit_income": "ਆਮਦਨ ਸੰਪਾਦਿਤ ਕਰੋ",
    "edit_expense": "ਖਰਚ ਸੰਪਾਦਿਤ ਕਰੋ",
    "income_category": "ਆਮਦਨ ਕੈਟੇਗਰੀ",
    "expense_category": "ਖਰਚ ਕੈਟੇਗਰੀ",
    "transaction_date": "ਲੇਨ-ਦੇਨ ਦੀ ਮਿਤੀ",
    "enter_transaction_amount": "ਲੇਨ-ਦੇਨ ਰਕਮ ਦਾਖਲ ਕਰੋ",
    "delete": "ਹਟਾਓ",
    "save": "ਸੰਭਾਲੋ",
    "expiry_date": "ਮਿਆਦ ਦੀ ਮਿਤੀ",
    "current_stock": "ਮੌਜੂਦਾ ਭੰਡਾਰ",
    "current_need": "ਮੌਜੂਦਾ ਜ਼ਰੂਰਤ",
    "add_feed_item": "ਚਾਰਾ ਆਈਟਮ ਸ਼ਾਮਲ ਕਰੋ",
    "item_name": "ਆਈਟਮ ਦਾ ਨਾਮ",
    "quantity": "ਮਾਤਰਾ",
    "required_quantity": "ਲੋੜੀਦਾ ਮਾਤਰਾ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "edit_feed_item": "ਚਾਰਾ ਆਈਟਮ ਸੋਧੋ",
    "need": "ਲੋੜ",
    "stock": "ਸਟਾਕ",
    'Born on Farm':'ਖੇਤ ਚ ਪੈਦਾ ਹੋਇਆ',
  "DairyMate Registration": "ਡੇਅਰੀਮੇਟ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
  "Join an Existing Farm": "ਮੌਜੂਦਾ ਖੇਤ ਨਾਲ ਜੁੜੋ",
  "Get started with your farm management journey": "ਆਪਣੀ ਫਾਰਮ ਪ੍ਰਬੰਧਨ ਯਾਤਰਾ ਦੀ ਸ਼ੁਰੂਆਤ ਕਰੋ",
  "Confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
  "Sign Up": "ਰਜਿਸਟਰ ਕਰੋ",
  "Enter Your Phone Number": "ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
  "Phone Number": "ਫ਼ੋਨ ਨੰਬਰ",
  "Login To DairyMate": "ਡੇਅਰੀਮੇਟ ਵਿੱਚ ਲੌਗਿਨ ਕਰੋ",
  "Didn't receive code?": "ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ?",
  "Resend OTP": "ਓਟੀਪੀ ਮੁੜ ਭੇਜੋ",
  "Continue": "ਜਾਰੀ ਰੱਖੋ",
  "Enter OTP": "ਓਟੀਪੀ ਦਰਜ ਕਰੋ",
  "Register a New Farm": "ਨਵਾਂ ਫਾਰਮ ਰਜਿਸਟਰ ਕਰੋ",
    'Purchased':'ਖਰੀਦਿਆ ਗਿਆ',
    "new_cattle_added_successfully": "ਨਵੀਂ ਪਸ਼ੂ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ ਹੈ",
    'notifications':"ਸੂਚਨਾਵਾਂ",
    "provide nutritional feed with high protein and fibre content": "ਉੱਚ ਪ੍ਰੋਟੀਨ ਅਤੇ ਫਾਈਬਰ ਸਮੱਗਰੀ ਵਾਲਾ ਪੋਸ਼ਣ ਚਾਰਾ ਪ੍ਰਦਾਨ ਕਰੋ", // Nutritional alert
    "is expected to go dry": "ਸੂਕਾ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ ਹੈ", // Dry alert
    "Heat alert": "ਗਰਮੀ ਦੀ ਚੇਤਾਵਨੀ", // Heat alert for cattle
    "is due for pregnancy test": "ਗਰਭਧਾਰਣ ਟੈਸਟ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ", // Pregnancy Test alert
    "is due for calving": "ਬੱਛੇ ਦੇ ਜਨਮ ਦਾ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ", // Calving alert
    "is ready for milking": "ਦੁੱਧ ਦੁਹਾਈ ਲਈ ਤਿਆਰ ਹੈ", // Milking alert after calving
    "is due for Insemination": "ਕ੍ਰਿਤਰਿਮ ਗਰਭਧਾਰਣ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ", // Artificial Insemination alert for Heifers
    "is due for deworming vaccination": "ਕੀੜੇ ਮਾਰ ਟੀਕੇ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ", // Deworming vaccination alert
    "is due for brucellosis vaccination": "ਬਰੂਸੈਲੋਸਿਸ ਟੀਕੇ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ", // Brucellosis vaccination alert
    "is due for modified theileriosis vaccination": "ਸੋਧਿਤ ਥਾਈਲਰੀਓਸਿਸ ਟੀਕੇ ਲਈ ਸਮਾਂ ਹੋ ਗਿਆ ਹੈ",// Modified Theileriosis vaccination alert,
  "Dry Alert": "ਸੂਖਾ ਚੱਕਰ ਚੇਤਾਵਨੀ",
  "Heat Alert": "ਗਰਮੀ ਦੀ ਚੇਤਾਵਨੀ",
  "Pregnancy Test Alert": "ਗਰਭਧਾਰਣ ਟੈਸਟ ਚੇਤਾਵਨੀ",
  "Calving Alert": "ਬੱਛੇ ਦੇ ਜਨਮ ਦੀ ਚੇਤਾਵਨੀ",
  "Milking Alert": "ਦੁੱਧ ਦੁਹਾਈ ਚੇਤਾਵਨੀ",
  "AI Alert": "ਕ੍ਰਿਤਰਿਮ ਗਰਭਧਾਰਣ ਚੇਤਾਵਨੀ",
  "Deworming Vaccine Alert": "ਕੀੜੇ ਮਾਰ ਟੀਕੇ ਦੀ ਚੇਤਾਵਨੀ",
  "Brucellosis Vaccine Alert": "ਬਰੂਸੈਲੋਸਿਸ ਟੀਕੇ ਦੀ ਚੇਤਾਵਨੀ",
  "Modified Theileriosis Vaccine Alert": "ਸੋਧਿਤ ਥਾਈਲਰੀਓਸਿਸ ਟੀਕੇ ਦੀ ਚੇਤਾਵਨੀ",
    "Nutritional Feed Alert": "ਪੋਸ਼ਣ ਚਾਰਾ ਚੇਤਾਵਨੀ",
  "Cow": "ਗਾਂ",
  "Buffalo": "ਭੈਂਸ",
    "Total Milk": "ਕੁੱਲ ਦੁੱਧ",
    "Litres": "ਲਿਟਰ",
    "unknown_item": "ਅਣਜਾਣ ਆਈਟਮ",
    // "quantity": "ਮਾਤਰਾ",
    "Rate": "ਦਰ",
    // "date": "ਤਾਰੀਖ",
    "Source": "ਸਰੋਤ",
    "green_fodder": "ਹਰਾ ਚਾਰਾ",
    "dry_fodder": "ਸੁੱਕਾ ਚਾਰਾ",
    "concentrate": "ਘਣੀ ਚਾਰਾ",
    "Own Farm": "ਖੁਦ ਦਾ ਫਾਰਮ",
    // 'Others': 'ਹੋਰ',
    'Enter custom type': 'ਕਸਟਮ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    // 'Source': 'ਸਰੋਤ',
    // 'Purchased': 'ਖਰੀਦਿਆ',
    // 'Own Farm': 'ਆਪਣੀ ਖੇਤੀ',
    'Quantity': 'ਮਾਤਰਾ',
    'Unit': 'ਇਕਾਈ',
    'Kg': 'ਕਿਲੋਗ੍ਰਾਮ',
    'Quintal': 'ਕੁਇੰਟਲ',
    'Rate per Unit': 'ਇਕਾਈ ਪ੍ਰਤੀ ਦਰ',
    'Total Price': 'ਕੁੱਲ ਕੀਮਤ',
    'Calculate': 'ਗਣਨਾ ਕਰੋ',
    'Save': 'ਸੇਵ ਕਰੋ',
    'Type': 'ਕਿਸਮ',
    'Quantity/Yield': 'ਮਾਤਰਾ / ਪੈਦਾਵਾਰ',
    'Land Area(in acres)': 'ਜਮੀਨ ਦਾ ਖੇਤਰਫਲ (ਏਕੜਾਂ ਵਿੱਚ)',
    'Seed Cost': 'ਬੀਜ ਦੀ ਲਾਗਤ',
    'Fertilizers Cost': 'ਖਾਦ ਦੀ ਲਾਗਤ',
    'Inoculants Cost': 'ਇਨੋਕੁਲੈਂਟਸ ਦੀ ਲਾਗਤ',
    'Labor Cost': 'ਮਜਦੂਰੀ ਦੀ ਲਾਗਤ',
    'Diesel Cost': 'ਡੀਜ਼ਲ ਦੀ ਲਾਗਤ',
    'Total Production Cost': 'ਕੁੱਲ ਉਤਪਾਦਨ ਦੀ ਲਾਗਤ',
    'Homemade': 'ਘਰੇਲੂ',
    'Enter Custom Homemade Type': 'ਕਸਟਮ ਘਰੇਲੂ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    'Select Ingredients:': 'ਸਮਗਰੀ ਚੁਣੋ:',
    'Enter its cost': 'ਇਸ ਦੀ ਕੀਮਤ ਦਰਜ ਕਰੋ',
    'Custom Type cannot be empty!': 'ਕਸਟਮ ਕਿਸਮ ਖਾਲੀ ਨਹੀਂ ਹੋ ਸਕਦੀ!',
    'Enter Custom Purchased Type': 'ਕਸਟਮ ਖਰੀਦਿਆ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    // 'Select Ingredients:': 'ਸਮਗਰੀ ਚੁਣੋ:',
    'Purchased Ingredients': 'ਖਰੀਦੀਆਂ ਸਮਗਰੀਆਂ',
    'Homemade Ingredients': 'ਘਰੇਲੂ ਸਮਗਰੀਆਂ',
    'Total Income': 'ਕੁੱਲ ਆਮਦਨ',
    // 'Enter Custom Purchased Type': 'ਕਸਟਮ ਖਰੀਦਿਆ ਕਿਸਮ ਦਰਜ ਕਰੋ',
    "Search Cattle": "ਪਸ਼ੂ ਖੋਜੋ"

  };
}
