class LocalizationHi {
  static const Map<String, String> translations = {
    'cattle': 'पशु',
    'Register a New Farm': 'नया फार्म पंजीकृत करें',
    'feed': 'चारा',
    'Cow': 'गाय',
    'Buffalo': 'भैंस',
    'transaction': 'लेन-देन',
    'avg_milk': 'औसत दूध',
    'dry_cows': 'सूखी गायें',
    'RF ID': "पशु आईडी",
    'Search Cattle': 'पशु खोजें',
    'breed': 'नस्ल',
    'sex': 'लिंग',
    'new_cattle': 'नये पशु',
    'enter_the_rfid': 'आरएफआईडी दर्ज करें ',
    'gender': 'लिंग',
    'enter_the_DOB': 'जन्मतिथि दर्ज करें',
    'enter_the_weight': 'वजन दर्ज करें ',
    'source_of_cattle': 'पशुओं का स्रोत',
    'select_the_breed': 'नस्ल चुनें',
    'status': 'स्थिति',
    'isPregnant': 'गर्भवती है',
    'no': 'नहीं',
    'yes': 'हाँ',
    'male': 'नर',
    'female': 'मादा',
    'born on farm': 'खेत में जन्मा',
    'purchased': 'खरीदा गया',
    'Select Ingredients:': 'सामग्री चुनें:',
    'Milked': 'दुही',
    'milked': 'दुही',
    'Heifer': 'बछिया',
    'insemination': 'गर्भाधान',
    'abortion': 'गर्भपात ',
    'Dry': 'सूखी',
    'dry': 'सूखी',
    'calf': 'बछड़ा',
    'Calf': 'बछड़ा',
    "Animals": "पशु",
    "Green Fodder": "हरा चारा",
    "Dry Fodder": "सूखा चारा",
    "Concentrate": "संघनित चारा",
    "unknown_item": "अज्ञात आइटम",
    'Enter custom type': 'कृपया प्रकार दर्ज करें',
    "quantity": "मात्रा",
    "Quantity": "मात्रा",
    'Wheat Straw': 'गेहूं का भूसा',
    'Paddy Straw': 'धान का भूसा',
    'Enter Custom Purchased Type': "कस्टम खरीदी गई प्रकार दर्ज करें",
    'Enter Custom Homemade Type': "कस्टम घरेलू प्रकार दर्ज करें",
    'Enter its cost': 'इसकी लागत दर्ज करें',
    'Custom Type cannot be empty!': 'कस्टम प्रकार खाली नहीं हो सकता है!',
    'Mustard': 'सरसों',
    'Maize': 'मक्का',
    'Barley': 'जौ',
    'De-Oiled Rice Bran': 'डी-ऑयल्ड चावल की भूसी',
    'Soyabean': 'सोयाबीन',
    'Wheat Bran': 'गेहूं की भूसी',
    'DCP': 'डीसीपी',
    'LSP': 'एलएसपी',
    'Salt': 'नमक',
    'Sodium Bicarbonate': 'सोडियम बाइकार्बोनेट',
    'Nicen': 'नाइसिन',
    'Urea': 'यूरिया',
    'Mineral Mixture': 'खनिज मिश्रण',
    'Others': 'अन्य',
    'homemade': 'घरेलू',
    "Rate": "दर",
    "date": "तारीख",
    "Source": "स्रोत",
    'own farm': "स्वयं का फार्म",
    'Quantity/Yield': "उत्पादन / मात्रा",
    "Rate per Unit": "प्रति इकाई दर",
    "Total Price": "कुल मूल्य",
    "Land Area(in acres)": "भूमि क्षेत्रफल (एकड़ में)",
    "Seed Cost": "बीज लागत",
    "Fertilizers Cost": "उर्वरक लागत",
    "Inoculants Cost": "इनोकुलेंट्स लागत",
    "Labor Cost": "श्रम लागत",
    "Diesel Cost": "डीजल लागत",
    "Total Production Cost": "कुल उत्पादन लागत",
    "Calculate": "गणना करें",
    "Save": "सहेजें",
    'calved': 'वाछ ब्याई गाय',
    'pregnant': 'गर्भवती',
    'submit': 'प्रस्तुत',
    'search_cattle': 'पशु खोजें',
    'state': 'स्थिति',
    'sahiwal': 'सहिवाल',
    'gir': 'गिर',
    'jersey': 'जर्सी',
    'holstein': 'होल्स्टीन',
    'Rye Grass': 'राई घास',
    'Bajra': 'बाजरा',
    'Sorghum': 'ज्वार',
    'Berseem': 'बरसीम',
    'Oats': 'जई',
    'all': 'सभी',
    'filter_options': 'फ़िल्टर विकल्प',
    'confirm_filters': 'फ़िल्टर सत्यापित करें',
    'clear_filters': 'फ़िल्टर मिटाएं',
    'vaccination': 'टीकाकरण',
    'please_wait': 'कृपया प्रतीक्षा करें ...',
    'events': 'घटनाएं',
    "add_event": "घटनाएँ जोड़ें",
    'details': "विवरण",
    "age": "आयु",
    "dob": "जन्म तिथि",
    "weight": "वज़न",
    "Total Count": "कुल गिनती",
    'Total Income': 'कुल आय',
    "semen sale": "वीर्य बिक्री",
    "milk_records": "दूध का रिकॉर्ड",
    "Total Milk": "कुल दूध",
    "litre": "लि.",
    "Litres": "लीटर",
    "add_milk_data": "दूध का डेटा जोड़ें",
    "select_rfid": "आरएफआईडी का चयन करें",
    "morning_milk": "सुबह का दूध (लीटर)",
    "evening_milk": "शाम का दूध (लीटर)",
    "milking_date": " दूध निकालने की तारीख",
    "add": "जोड़ें",
    "please_select_rfid": "कृपया आरएफआईडी का चयन करें",
    "please_enter_value": "कृपया मूल्य दर्ज करें",
    "please_choose_date": "कृपया एक तारीख चुनें",
    "morning": "सुबह",
    "evening": "शाम",
    "total": "कुल",
    "milk_sale": "दूध बिक्री",
    "cattle_sale": "पशु बिक्री",
    "other": "अन्य",
    "income": "आय",
    "expenses": "व्यय",
    "transactions": "लेन-देन",
    "amount": "राशि",
    "on_date": "तिथि",
    "Feed": "चारा",
    "Inventory": "भंडार",
    "Veterinary": "पशुचिकित्सा",
    "Labor Costs": "श्रम लागत",
    "Equipment and Machinery": "उपकरण और मशीनरी",
    "total_transactions": "कुल लेन-देन",
    "date_range": "तिथि सीमा:",
    "total_income": "कुल आय",
    "income_per_category": "विभाग आय",
    "total_expense": "कुल व्यय",
    "expense_per_category": "विभाग व्यय",
    "net_profit": "नेट लाभ",
    "net_loss": "नेट हानि",
    "Milk Details": "दूध का विवरण",
    "Milk Sale": "दूध बिक्री",
    "Cattle Sale": "पशु बिक्री",
    "date_of_income": "आय की तारीख",
    "how_much_did_you_earn": "आपने कितना कमाया (₹ में)",
    "select_income_type": "आय का प्रकार चुनें",
    "enter_category": "वर्ग दर्ज करें",
    "new_income": "नई आय",
    "Other": "अन्य",
    'Select Buyer': 'क्रेता का चयन करें',
    'Nutritional Feed Alert': 'पोषण आहार चेतावनी',
    "Dry Alert": "सूखा चक्र अलर्ट",
    "Heat Alert": "गर्मी का अलर्ट",
    "Pregnancy Test Alert": "गर्भावस्था परीक्षण अलर्ट",
    "Calving Alert": "बच्चे के जन्म का अलर्ट",
    "Milking Alert": "दूध दुहाई का अलर्ट",
    "AI Alert": "कृत्रिम गर्भाधान अलर्ट",
    "Deworming Vax Alert": "कीड़ों की दवाइयों का टीका अलर्ट",
    "Brucellosis Vax Alert": "ब्रूसलोसिस टीका अलर्ट",
    "Modified Theileriosis Vax Alert": "संशोधित थिलेरियोसिस टीका अलर्ट",
    "Dairy Sangrah Registration": "डेरी संग्रह पंजीकरण",
    "Get into Existing Farm": "मौजूदा फार्म में प्रवेश करें",
    "Get started with your farm management journey":
        "अपने फार्म प्रबंधन यात्रा की शुरुआत करें",
    "Confirm": "पुष्टि करें",
    "Sign Up": "रजिस्टर करें",
    "Enter Your Phone Number": "अपना फोन नंबर दर्ज करें",
    'Phone Number': 'फोन नंबर',
    "Login To Dairy Sangrah": "डेरी संग्रह में लॉगिन करें",
    "Didn't receive code?": "कोड प्राप्त नहीं हुआ?",
    "Resend OTP": "ओटीपी दोबारा भेजें",
    "Continue": "जारी रखें",
    "Enter OTP": "ओटीपी दर्ज करें",
    "provide nutritional feed with high protein and fibre content":
        "उच्च प्रोटीन और फाइबर सामग्री वाला पोषक चारा प्रदान करें",
    "is expected to go dry": "सूखा होने की संभावना है",
    "Heat alert": "गर्मी का अलर्ट",
    "is due for pregnancy test": "गर्भावस्था परीक्षण के लिए समय आ गया है",
    "is due for calving": "बच्चे के जन्म का समय आ गया है",
    "is ready for milking": "दूध दुहाई के लिए तैयार है",
    "is due for Insemination": "कृत्रिम गर्भाधान के लिए समय आ गया है",
    "is due for deworming vaccination": "कीड़े मारने के टीके का समय आ गया है",
    "is due for brucellosis vaccination": "ब्रूसलोसिस के टीके का समय आ गया है",
    "is due for modified theileriosis vaccination":
        "संशोधित थिलेरियोसिस के टीके का समय आ गया है",
    'Fat Percentage': 'वसा प्रतिशत',
    'SNF Percentage': 'एसएनएफ प्रतिशत',
    'Quantity (Liters)': 'मात्रा (लीटर में)',
    "new_expense": "नया व्यय",
    "date_of_expense": "व्यय की तारीख",
    "how_much_did_you_spend": "आपने कितना व्यय किया (₹ में)",
    "select_expense_type": "व्यय का प्रकार चुनें",
    "edit_income": "आय संपादित करें",
    "edit_expense": "व्यय संपादित करें",
    "income_category": "आय वर्ग",
    "expense_category": "व्यय वर्ग",
    "transaction_date": "लेन-देन की तारीख",
    "enter_transaction_amount": "लेन-देन राशि दर्ज करें",
    "delete": "हटाएं",
    "save": "सहेजें",
    'Type': 'प्रकार',
    "expiry_date": "समाप्ति तिथि",
    "current_stock": "वर्तमान भंडार",
    "current_need": "वर्तमान आवश्यकता",
    "add_feed_item": "चारा आइटम जोड़ें",
    "item_name": "आइटम का नाम",
    "required_quantity": "आवश्यक मात्रा",
    "category": "श्रेणी",
    "edit_feed_item": "चारा आइटम संपादित करें",
    "need": "आवश्यकता",
    "stock": "स्टॉक",
    "new_cattle_added_successfully": "नई पशु सफलतापूर्वक जोड़ा गया",
    'notifications': "सूचनाएं",
    'No existing Farm!': 'कोई मौजूदा खेत नहीं है!',
    'Not Registered Content':
        "इस नंबर के साथ कोई फ़ार्म पंजीकृत नहीं है। कृपया नया फ़ार्म पंजीकृत करने के लिए 'रजिस्टर' चुनें या पीछे जाने के लिए 'रद्द करें' चुनें!",
    'register': 'रजिस्टर',
    'cancel': 'रद्द करें',
    'Owner Name': 'मालिक का नाम',
    'Phone No.': 'फ़ोन नंबर',
    'Farm Name': 'फ़ार्म का नाम',
    'Farm Address': 'फ़ार्म का पता',
    'Profile': 'प्रोफ़ाइल - व्यक्तिगत विवरण',
    'Log out': 'लॉग आउट करें',
    'Delete Data': 'डेटा हटाएं',
    "Are you Sure?": 'क्या आप सुनिश्चित हैं?',
    'Delete Data Content':
        "यह क्रिया सभी फ़ार्म डेटा को को हमेशा के लिए हटा देगी, लेकिन फ़ार्म अभी भी पंजीकृत रहेगा। कृपया आगे बढ़ने के लिए 'हाँ' चुनें या वापस जाने के लिए 'रद्द करें' चुनें!",
    'Delete Account': 'खाता हटाएं',
    'Delete Account Content':
        "यह क्रिया आपके सभी यूज़र और फ़ार्म डेटा को हमेशा के लिए हटा देगी। कृपया आगे बढ़ने के लिए 'हटाएं' चुनें या वापस जाने के लिए 'रद्द करेंं' चुनें!",
    're-login': 'फिर से लॉगिन करें',
    'requires recent login': 'हाल ही में लॉगिन किया होना ज़रूरी है!',
    're_login content':
        "कृपया 'फिर से लॉगिन करें' चुनें और फिर से प्रयास करें, या 'रद्द करेंं' चुनें वापस जाने के लिए!",
    'More Options': 'और विकल्प',
    'Edit Profile': 'प्रोफ़ाइल बदलें',
    'Error in Fetch': 'डेटा प्राप्ति में त्रुटि',
    'Save Changes': 'बदलाव सहेजें',
    'Deleted': 'हटा दिया गया',
    'edit_details': 'विवरण बदलें',
    'please_select_gender': 'कृपया लिंग चुनें',
    'please_select_source': 'कृपया स्रोत चुनें',
    'please_select_breed': 'कृपया नस्ल चुनें',
    'cattle_details_updated_successfully': 'विवरण सफलतापूर्वक अपडेट हुआ!!',
    'event_name': 'घटना का नाम',
    'event_date': 'घटना का तारीख',
    'please_select_event_and_date': 'कृपया एक घटना और तारीख चुनें',
    'rfid_already_exists': 'आरएफआईडी पहले से मौजूद है',
    'please_enter_tag_num': 'कृपया टैग नंबर दर्ज करें',
    'please_select_cattle_type': 'कृपया पशु का प्रकार चुनें',
    'list_is_empty': 'सूची खाली है',
    'no_entries_for_sel_date': 'चुनी गई तारीख में कोई प्रविष्टि नहीं है!',
    'edit_milk_data': 'दूध का डेटा संपादित करें',
    'enter_valid_num': 'सही संख्या दर्ज करें',
    'add_transaction': 'लेन-देन जोड़ें',
    'no_matching_price': 'मेल खाती कीमत नहीं मिली -',
    'fat': 'फैट',
    'snf': 'एसएनएफ',
    'err_msg': 'त्रुटि संदेश',
    'OK': 'ठीक है',
    'please_sel_income_type': 'कृपया एक आय प्रकार चुनें',
    'please_enter_category_other':
        "कृपया 'अन्य' आय प्रकार के लिए एक श्रेणी दर्ज करें",
    'please_sel_milk_buyer': 'कृपया एक दूध खरीदार चुनें',
    'please_sel_fat_snf_qty': 'कृपया फैट, एसएनएफ, और मात्रा के मूल्य दर्ज करें',
    'fat_snf_qty_val_chk':
        'फैट, एसएनएफ, और मात्रा के मूल्य संख्याएँ होनी चाहिए जो शून्य से बड़ी हों',
    'no_price_fat_snf': 'दिए गए फैट और एसएनएफ के लिए दूध मूल्य डेटा नहीं मिला',
    'please_enter_tot_income': 'कृपया कुल आय दर्ज करें',
    'sel_feed_consumption': 'चारे की खपत चुनें :',
    'out_of_stock': 'स्टॉक समाप्त, कृपया पुनः भरें!',
    'enter_qty_consumed_kg': 'उपयोग की गई मात्रा (किलो में) दर्ज करें',
    'cannot_be_more_than_existing': 'मौजूदा मात्रा से अधिक नहीं हो सकती!',
    'Unit': 'इकाई',
    'Kg': 'किलो',
    'Quintal': 'क्विंटल',
    "amul": "अमूल",
    "verka": "वेरका",
    "nestle": "नेस्ले",
    "d to c": "सीधे ग्राहक तक",
    'start': 'प्रारंभ',
    'end': 'अंत',
    'data_del_msg': 'कृपया प्रतीक्षा करें, डेटा हटाया जा रहा है!',
    "Land Area (in acres)": "भूमि क्षेत्रफल (एकड़ में)",
    "app_version": "ऐप संस्करण",
    "Select Language": "भाषा चुनें",
    "English": "अंग्रेज़ी",
    "Hindi": "हिंदी",
    "Punjabi": "पंजाबी",
    "Telugu": "तेलुगु",
    "Preferred Language": "पसंदीदा भाषा",
  };
}
