// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALWWg6zUU0KsjClXs9SvX_5q30tOLMTSw',
    appId: '1:856392093031:android:80d8942dcdf878ed33b3c2',
    messagingSenderId: '856392093031',
    projectId: 'farm-expense-management-cp',
    storageBucket: 'farm-expense-management-cp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEBroxwravOFvgMLexWrAWPrmMzvvYD0w',
    appId: '1:856392093031:ios:73515d3a64ecfc4233b3c2',
    messagingSenderId: '856392093031',
    projectId: 'farm-expense-management-cp',
    storageBucket: 'farm-expense-management-cp.firebasestorage.app',
    androidClientId: '856392093031-7870h58t99nesivpf0g3t4ppovaf2foq.apps.googleusercontent.com',
    iosClientId: '856392093031-87h0hg5d2bi5v6ruaj13mabo6f37jcv7.apps.googleusercontent.com',
    iosBundleId: 'com.awadh.farmExpenseMangementApp',
  );

}